### ISSUE TITLE
Investigate cascading update during properties panel resize

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1093]
__Describe the Bug__

For each drag event, we cause two tree reconcilation one after another. This is probably caused by state or props change during event handling. Fixing this could improve performance.

![screenshot 2019-01-10 at 16 40 16](https://user-images.githubusercontent.com/28307541/50979662-43e3f000-14f7-11e9-9119-c7ff4ba7ed3b.png)

__Steps to Reproduce__

1. Turn on performance recording.
2. Drag properties panel handle

__Expected Behavior__

At most one update per event.

__Environment__

Please complete the following information:

 - OS: macOS 10.14.2
 - Camunda Modeler Version: `next`

**Comment by nikku** [comment]
The flame graph shown reveals our slot-fill pattern at work.

In order to function correctly it will always execute the following:

* Fill content changes trigger fill update / reregistration (on `componentDidUpdate`)
* Slot will update on next tick (triggered via `setState(...)`)

We'll probably not be able to work around that situation, unless we hack around the internals of ReactJS.

**Comment by nikku** [comment]
We are fast enough right now and will follow up with respective improvements once we see the need for them.
