### ISSUE TITLE
Investigate how to test the app

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#12]

**Comment by pedesen** [comment]
Intermediate state:
- It is possible to do unit and integration tests on the client part of the modeler using mocha.
- This project might be useful to integrate mocha: https://github.com/jprichardson/electron-mocha
- The backend (app) part of the modeler, especially some electron modules (menus, native dialogues, ...) are not part of the DOM, which is why integration tests on them are non trivial.

Open questions:
- Do we need integration tests on the backend and on electron modules? How to implement them?
- How to test features which are more or less depending on the operating system (like file associations, drag and drop files)?

**Comment by nikku** [comment]
Fixed.
