### ISSUE TITLE
I can choose implementation type "external" for intermediate message throw events

### ISSUE THREAD

**Issue by jhorstmann** [camunda/camunda-modeler#122]
As I understand it message throw events should behave the same way as service tasks

**Comment by meyerdan** [comment]
Legit. Type external is supported for intermediate message throw events. Should be possible to configure this in PP.

Issue needs to be opened in bpmn-io/bpmn-js-properties-panel

**Comment by meyerdan** [comment]
Sorry, my Bad, Rollback:
The External Task functionality is only officially supported for ServiceTasks.
The documentation states it like this and we only have testcases for ServiceTasks.
Given the way it is implemented, it *should* work for other task types as well but this is not an official feature.

So in order to have this funcitonality we need to first implement it in engine (effectively write test cases) and then implement it in modeler

**Comment by ThorbenLindhauer** [comment]
Camunda BPM JIRA ticket: https://app.camunda.com/jira/browse/CAM-4690

**Comment by meyerdan** [comment]
Moddle issue: camunda-bpmn-moddle/issues/25

**Comment by gimbel** [comment]
@romansmirnov  Did we solve this issue in the properties panel?

**Comment by romansmirnov** [comment]
@gimbel If we solve this issue https://github.com/camunda/camunda-bpmn-moddle/issues/25 than it should work out of the box in the properties panel.

**Comment by gimbel** [comment]
I changed the milestone of this one so that we are reminded to actively decide on this one

**Comment by gimbel** [comment]
@romansmirnov  Can this ticket be closed?

**Comment by romansmirnov** [comment]
@gimbel Yes
