### ISSUE TITLE
Wrong Z-Order when moving BPMN Elements into Sub-Process

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#1326]
__Describe the Bug__

Here is a screenshot from Trisotech that shows how the flow nodes of the sub-process appear to be behind (note the shading) while the sequence flows are correctly on top:
![phase1-trisotech](https://user-images.githubusercontent.com/40038/54700133-aaf2d600-4b32-11e9-8e5a-9e337428d4bb.jpg)

__Steps to Reproduce__

1. Create some flow nodes and connect them with sequence flows.
2. Create a sub-process
3. Move the previously created elements into the sub-process
4. Save the file and open it in a different BPMN tool, e.g. Trisotech

__Expected Behavior__

Flow nodes are on top of the sub-process.

__Environment__

Please complete the following information:

 - OS: Ubuntu 18.04.2 LTS
 - Camunda Modeler Version: 3.0.0-nightly of 2019-03-20

Here is the BPMN file with the wrong order:
[phase1.zip](https://github.com/camunda/camunda-modeler/files/2989099/phase1.zip)

This issue has been discovered during the preparation for the upcoming BPMN MIWG demo in June 2019 in Amsterdam.

---

Depends on https://github.com/bpmn-io/bpmn-js/issues/985.

**Comment by falko** [comment]
Here is my second try where I used copy & paste to put the contents into the sub-process and Trisotech confirmed that this looked okay:
[phase1-2nd-try.zip](https://github.com/camunda/camunda-modeler/files/2998095/phase1-2nd-try.zip)

**Comment by nikku** [comment]
I've looked into the issue, especially at the positions these elements reside in the DI section and found the following:

```
phase1.bpmn -> Manage Booking (SubProcess) DI at position 236
phase1.bpmn -> Book Flight (Task) DI : 148

phase1-2nd-try.bpmn -> Manage Booking (SubProcess) DI : 616
phase1-2nd-try.bpmn -> Book Flight (Task) DI : 625
```

As you can see, the `Book Flight` task is correctly placed after the sub process once you create the situation via copy and paste. It is incorrectly contained in the DI _before_ the `Manage Booking` sub process when you move elements into the sub process.

We (i.e. our toolkits) do not take into account the order in which elements appear in the DI section. The reason is that we found way to many tools mess up the DI section element order.

Apparently, Trisotec gives a thing about the order in the DI section though, otherwise they would not show the elements as greyed out. 

I did not find a section in the BPMN spec that talks about how to handle DI element order. Is there such thing? Otherwise it could be a good test case for a MIWG interchange working group sample.

**Comment by falko** [comment]
Hi @nikku,

on page 368 (PDF 398) of the BPMN 2.0.2 Spec it is stated:
> The order of the BPMNShape(s) and BPMNEdge(s) inside a BPMNPlane determines their Z-order (i.e., what is in front of what). BPMNShape(s) and BPMNEdge(s) that are meant to be depicted “on top” of other BPMNShape(s) and BPMNEdge(s) MUST appear after them in the BPMNPlane. Therefore, the exporting tool MUST order all BPMNShape(s) and BPMNEdge(s) such that the desired depiction can be rendered.

If other tools are messing up the z-order, they are not BPMN conformant. The BPMN MIWG regularly finds z-order issues in new BPMN implementations and asks the vendors to repair their tools.

Cheers,
Falko

**Comment by nikku** [comment]
Thanks for the clarification. We'll schedule a fix. 

:heart_eyes:

**Comment by nikku** [comment]
Tracked by [upstream bug](https://github.com/bpmn-io/bpmn-js/issues/985).

**Comment by nikku** [comment]
As the desired reordering behavior is hard to accomplish during modeling, ordering the DI elements as a pre-export step could be a viable solution.

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1730
