### ISSUE TITLE
Unsaved Changes Lost When Switching Back and Forth between Tabs

### ISSUE THREAD

**Issue by jwhoeche** [camunda/camunda-modeler#1347]
__Description__

When I open a new diagramm the changes in my first diagramm are undone.
**All diagramms** that are opened in XML View are reloaded  and all changes are removed.

__Steps to Reproduce__

1. Open a diagramm (or create a diagramm)
2. Change something in the diagramm
3. Switch to XML View of the diagramm
4. Create a new diagramm (File -> new File -> ... or Cntl +T have the same effect)
5. Go back to the first diagramm (all changes are undone)

__Expected Behavior__

When I open a new diagramm the other diagrammes should not be changed.

__Environment__

- Windows 10
- Modeler 3.0
- Plugin: camunda-modeler-property-info-plugin

**Comment by philippfromme** [comment]
I can reproduce this. Thanks for letting us know. We'll fix this ASAP.

![fail-compressed](https://user-images.githubusercontent.com/7633572/56272611-62abe100-60fb-11e9-8340-12535ddb69e9.gif)

**Comment by philippfromme** [comment]
The bug appears as soon as the sheet of a tab is switched with unsaved changes.

![foobar](https://user-images.githubusercontent.com/7633572/56650816-1b3bcc80-6688-11e9-968d-640f92d6eb4e.gif)

**Comment by philippfromme** [comment]
This bug was introduced by fixing https://github.com/camunda/camunda-modeler/issues/1318. Now that every time the `xml` prop passed from [App](https://github.com/camunda/camunda-modeler/blob/master/client/src/app/App.js#L1741) to [MultiSheetTab](https://github.com/camunda/camunda-modeler/blob/master/client/src/app/tabs/MultiSheetTab.js#L366) through [EditorTab](https://github.com/camunda/camunda-modeler/blob/master/client/src/app/tabs/EditorTab.js#L64) changes the cached `lastXML` property of MultiSheetTab is overridden the up-to-date XML that was cached after switching sheets will be replaced by the outdated XML passed to MultiSheetTab.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1356.

**Comment by nikku** [comment]
Released as [`v3.1.0`](https://github.com/camunda/camunda-modeler/releases/tag/v3.1.0)
