### ISSUE TITLE
Element templates relative to diagram are not available

### ISSUE THREAD

**Issue by tasso94** [camunda/camunda-modeler#1376]
This bug is not present for Camunda Modeler 2.2.4

__Describe the Bug__
No element template can be selected which is located relatively to the BPMN diagram.

__Steps to Reproduce__
1. Under `./bar/.camunda/element-templates/`, an element template `template.json` is placed
2. The BPMN diagram `foo.bpmn` is located under `./bar/` and contains a Service Task
3. I open the diagram by double click on `foo.bpmn` in the Finder

__Expected Behavior__
When selecting the Service Task in Camunda Modeler, I can choose the element template.

__Environment__
 - OS: macOS Sierra 10.12.6 (16G29)
 - Camunda Modeler Version: 3.1.0 (3.1.0.3470)

![image](https://user-images.githubusercontent.com/3015690/58019165-2d811d00-7b05-11e9-8538-723544dcc102.png)

**Comment by tasso94** [comment]
Element template:
```json
{
  "name": "Mail Task",
  "id": "com.camunda.example.MailTask",
  "appliesTo": [
    "bpmn:ServiceTask"
  ],
  "properties": [
    {
      "label": "Implementation Type",
      "type": "String",
      "value": "com.mycompany.MailTaskImpl",
      "editable": false,
      "binding": {
        "type": "property",
        "name": "camunda:class"
      }
    },
    {
      "label": "Sender",
      "type": "String",
      "binding": {
        "type": "camunda:inputParameter",
        "name": "sender"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "Receivers",
      "type": "String",
      "binding": {
        "type": "camunda:inputParameter",
        "name": "receivers"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "Template",
      "description": "By the way, you can use freemarker templates ${...} here",
      "value": "Hello ${firstName}!",
      "type": "Text",
      "binding": {
        "type": "camunda:inputParameter",
        "name": "messageBody",
        "scriptFormat": "freemarker"
      },
      "constraints": {
        "notEmpty": true
      }
    },
    {
      "label": "Result Status",
      "description": "The process variable to which to assign the send result to",
      "type": "String",
      "value": "mailSendResult",
      "binding": {
        "type": "camunda:outputParameter",
        "source": "${ resultStatus }"
      }
    }
  ]
}
```

**Comment by nedyalkonikolov** [comment]
I'm pasting a comment from a closed bug (I think that any new comment should re-open the issue)

There is a test for this feature (loading element templates from a directory relative to the diagram), but the test is using fake diagram object with a property "path"

https://github.com/camunda/camunda-modeler/blob/master/app/lib/client-config/__tests__/client-config-spec.js#L22-L25

therefore the code here:

https://github.com/camunda/camunda-modeler/blob/master/app/lib/client-config/providers/element-templates-provider.js#L40

passes the test.

Unfortunately the real object (diagram) does not have "path" property, but "file" object that have "path" property.

Code in element-templates-provider.js should
be
var localPaths = diagram && diagram.file ? parents(diagram.file.path) : [];

also test should be a little different ().

// given
var fakeDiagram = {
file: {
path: absPath('fixtures/project/bar.bpmn')
}
};

P.S. I do not find a document how to contribute, therefore I'm writing in the issue instead of a pull request! I hope someone from the core team could make this little change.

**Comment by pinussilvestrus** [comment]
@tasso94 Thanks for reporting!

@nedyalkonikolov Thanks for your investigations! We're open for contribution and would very appreciate your pull request. You can refer to the [Contribution guidelines of bpmn-js](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md) 😊

**Comment by barmac** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1379
