### ISSUE TITLE
Old bpmn files cannot be opened in newer Modelers

### ISSUE THREAD

**Issue by volkergersabeck** [camunda/camunda-modeler#1522]
__Describe the Bug__

We have a bpmn file that was created with Modeler version 2.2.4 and then uploaded to Cawemo. In Cawemo the diagram cannot be opened. When opening the file in Modeler versions 3.2.0 and newer, the file cannot be rendered and the following log is shown:

```javascript
[/Users/XXXX/Downloads/XXXX.bpmn] no diagram to display
    at Object.handleDefinitions (webpack:///node_modules/bpmn-js/lib/import/BpmnTreeWalker.js:173:0)
    at file:///Volumes/Camunda%20Modeler%203.2.0/Camunda%20Modeler.app/Contents/Resources/app.asar/public/6.6.js:1:392700
    at file:///Volumes/Camunda%20Modeler%203.2.0/Camunda%20Modeler.app/Contents/Resources/app.asar/public/6.6.js:1:392723
    at this (webpack:///node_modules/bpmn-js/lib/Viewer.js:311:26)
    at open (webpack:///node_modules/bpmn-js/lib/Viewer.js:256:0)
    at file:///Volumes/Camunda%20Modeler%203.2.0/Camunda%20Modeler.app/Contents/Resources/app.asar/public/6.6.js:1:391731
    at file:///Volumes/Camunda%20Modeler%203.2.0/Camunda%20Modeler.app/Contents/Resources/app.asar/public/0.0.js:1:373393 [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]
```

__Expected Behavior__

* [ ] We show the `illegal id` warning (hidden right now)
* [ ] We show the error (diagram cannot be found)

__Current workaround__

Change the 'id' attribute of the bpmn:definitions tag such that it does not start with a number and the diagram is rendered properly.

__Environment__

 - OS: MacOS (but not relevant, same issue in Cawemo)
 - Camunda Modeler Version: 3.2.0 and newer

[sample-broken-file.bpmn.txt](https://github.com/camunda/camunda-modeler/files/3696273/sample-broken-file.bpmn.txt)

**Comment by pinussilvestrus** [comment]
For some reason, it does not fetch the `diagram` information from the `definitions` because of the invalid id ("2c630b7a-79b3-4ba2-9561-16888e348f64"), which is not allowed from [this commit](https://github.com/bpmn-io/moddle-xml/commit/3bb3e0288591027d71f4e5318da0d26264ded4d4) on.

The overall questions should be:
- Why does it not throw the original error ("'illegal ID ...")
- Do we want to permit this for old diagrams that worked in older versions? Why wanted to have this validation in the first place?

Investigations go on 🔍.

**Comment by nikku** [comment]
My few cents from the :couch_and_lamp::

> Why does it not throw the original error ("'illegal ID ...")?

This is a bug we should fix.

> Do we want to permit this for old diagrams that worked in older versions? Why wanted to have this validation in the first place?

We want people to migrate their diagrams. These diagrams are broken, as they contain invalid IDs in the XML. Note that such IDs have been created in _very rare cases_, only. We do not want old diagrams to be magically opened.

**Comment by pinussilvestrus** [comment]
We added the QName validation for good reasons (e.g. security/xss concerns).

My suggestion to "fix" this would be to display the correct error, so the user is notified about the malformed id and can correct it. What do you think @volkergersabeck?

**Comment by pinussilvestrus** [comment]
> Why does it now throw the original error ...

This is because we handle those parsing errors as warnings: cf. [`moddle-xml#read`](https://github.com/bpmn-io/moddle-xml/blob/1478eb581c1b2603cf5aa140f8fb957292b724fd/lib/read.js#L679)

![image](https://user-images.githubusercontent.com/9433996/66314701-b19d3b00-e914-11e9-8551-ac870b2572b3.png).

The error leads to the `definitions` are not parsed completely, so no `diagrams` will be available, which leads to the error shown above. Since no diagram is rendered, no warnings will be displayed.

**Comment by nikku** [comment]
We've decided that we will improve the situation in the following way: 

* the illegal ID warning is shown next to the error
