### ISSUE TITLE
As a user I am able to run a process right from the app

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1552]
__Is your feature request related to a problem? Please describe.__

Right now in order to run a deployed process instance people need to go to Camunda Tasklist or use the Camunda REST API to start the instance. Both ways are _not discoverable_ for users of the Modeler.

In the scope of the Modeler _we see the ability to run as an additional learning tool_. Users should be able to repeatedly run a modeled diagram and inspect in order to learn what executing a BPMN diagram means.

__Describe the solution you'd like__

Add the ability to start/run the currently opened diagram right from the app. Technically, this includes deploying the diagram and spawning an instance. 

A number of questions remain:

* How does the feature compare to the start instance feature that is part of Camunda Tasklist (see below)
* How does run integrate with deploy feature?
* Should we allow users to specify input data when starting an instance? In Camunda Tasklist, starting using a form is possible, passing business key and additional variables is allowed, too.
* After starting, should we link to Cockpit to inspect the running instance (not possible in CE, if instance already terminated)

__Describe alternatives you've considered__

* Do nothing
* Deep link to tasklist to run UI instead. This is supported in 7.12 [CAM-10927](https://app.camunda.com/jira/browse/CAM-10927).
---

__Additional context__

The following screen cast shows how running in Camunda Tasklist works right now:

![capture ooLqLw_optimized](https://user-images.githubusercontent.com/58601/67291724-417ce080-f4e2-11e9-92d6-8bf50d581278.gif)

A few shown features are 

* Running presents users a form to fill in required data, if form data is attached to the process
* The presence of the data is validated, too

![capture FgLXlO_optimized](https://user-images.githubusercontent.com/58601/67292110-daabf700-f4e2-11e9-9ca8-c710f0cb22c9.gif)

A few shown features are

* Running without form data attached (the expected behavior when running from the modeler) presents the user with a form in which she can input a business key as well as an optional set of additional variables
* Once the process is started, no link guides the user anywhere, i.e. to Cockpit

---

Related ideas on ProdPad: [#163](https://app.prodpad.com/ideas/163/canvas), [#167](https://app.prodpad.com/ideas/167/canvas)

**Comment by ingorichtsmeier** [comment]
What about adding a button to start instances separated from the deploy button?

Here you can start more than one instance of the process model and provide a detailed dialogue to enter data.

**Comment by pinussilvestrus** [comment]
[**Results of first paper prototyping session**](https://drive.google.com/open?id=1Y84WenoLOYmO-JlcyHh_NJoTksUuuJh9)

**Comment by pinussilvestrus** [comment]
Demo-Branch: https://github.com/camunda/camunda-modeler/pull/1571

Experimental Branch for decoupling: https://github.com/camunda/camunda-modeler/tree/1552-plugins-communication

**Comment by pinussilvestrus** [comment]
We had one [**User Test**](https://drive.google.com/open?id=15dDmf-oR5ecovPPB_3mDEpDdvYzbJ5R81aFTym2fFQM) today to test both demos

**Summary**

- We decided that we will go for the Two Modal Solution
    - Having two toolbar icons (deploy and run)
    - Add direct run with the first click
    - Fallback structure (if not deployed, go back to deploy modal)
    - Remove Link in run modal (or link to docs)
    - Add “Deployed + Run…” to run successfully notification
    - Remove variables for now
    - Auto-fill business key with default
- We will combine the two features as one plugin for now, since we see know scenario for now, where we want to exclude one from another (might change in the future!)
- Next Steps: 
    - Create final demo with modifications
    - Discuss it internally with the team
    - Discuss the wording

**Comment by pinussilvestrus** [comment]
Current State of the Implementation goes [here](https://github.com/camunda/camunda-modeler/pull/1577).

**Comment by pinussilvestrus** [comment]
Current Things are to do now to complete the overall workflow as we decided to have for the _Start Instance feature_, cf. https://github.com/camunda/camunda-modeler/pull/1577#issuecomment-552887300: 

* We need the success message after process was started to be a Notification, and no Modal, cf. #1580 
* We choose the wording "Start" instead of "Run"
* We need a two-step-modal wizard, which needs a way to _update_  the Deployment Details Model to fit into the _start instance_ interaction
* We need a two-step check before starting a process instance
   *  `ConnectionCheck`, as it is already inside the Deployment feature
   *  Another check, which verifies there exists a deployment for the current version of the diagram

Work continues in https://github.com/camunda/camunda-modeler/pull/1577, but for points 3 and 4 we should introduce the technical prerequisites via extra pull requests.

**Comment by pinussilvestrus** [comment]
#1577 includes now the workflow as we decided to have. The general implementation is blocked by the pending deployment UI improvements, cf. #1558

**Comment by pinussilvestrus** [comment]
Things to change under the hood to get the `StartInstanceTool` finished

* [ ] Change structure of the plugin

```js
deployRef = React.createRef();

<CamundaPlugin>
   <DeploymentTool ref={ deployRef } />
   <StartInstanceTool deployRef={ deployRef } />
</CamundaPlugin>
```

* [ ] Make `DeploymentConfigModal` configurable (title, intro and primary action label)
* [ ] Make `ConnectionChecker` reusable

Will likely push that changes as own pull request.
