### ISSUE TITLE
SPIKE: Deploy UI improvements

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1558]
#### Modal Basics

_To be solved in modal infrastructure (https://github.com/camunda/camunda-modeler/issues/1568):_

* [x] close button @barmac 
* [x] `ESC` inside a modal should close it @barmac 
* [x] header @barmac 
* [x] footer contains buttons @barmac 
* [x] trap tab navigation @barmac 

_To be solved by modal implementors:_

* [ ] disabled state should be inddicated
* [ ] primary secondry button

#### Deploy Details

* [x] (+) means add more of the same -> replace with arrow down / up @nikku 
* [ ] Don't show success, assume we are gut @nikku 
* [ ] get rid of general message, show message in elements that are related @nikku 

#### Notification Basics

* [ ] add color coding or icons

#### Other (focus later)

* [ ] make focus more visible / consistent across applications @nikku

**Comment by barmac** [comment]
@nikku Progress summary:

The checked modal basics features are already working and I pushed them on `1067-remember-authentication-details-with-endpoint-configuration`.

I started to work on the strict modal structure and it [is mostly done](https://github.com/camunda/camunda-modeler/pull/1526/commits/ef94117bf437f3abef37a138a7257768ed09fd50), except for the styling. However, I came across problems when implementing that structure in the `DeploymentDetailsModal`. Because the buttons of the form are [nested inside the form](https://github.com/camunda/camunda-modeler/pull/1526/commits/ed5fdae1ddac319e9d4ec17cbd41d612b34fdb7f#diff-91535a34b9a7ba22da11b761c2798361R297-R310) and depend on the Formik's `isSubmitting`, they can't be simply place in the `Modal.Footer`. We need to find a solution for that.

https://github.com/camunda/camunda-modeler/pull/1526/commits/fa72a7bde262146ace3723ec5ee1864b0a4052e3

**Comment by barmac** [comment]
I also made sure that no tests fail at the moment.

**Comment by nikku** [comment]
Progress update:

![modeler-design-spike_1](https://user-images.githubusercontent.com/58601/67562262-ac1a6000-f71e-11e9-8a12-994211d0e4a5.png)

**Comment by nikku** [comment]
Additional Idea for improvement, suggested by @philippfromme:

![image](https://user-images.githubusercontent.com/58601/67569449-3c60a100-f72f-11e9-9760-5bb94ffd3dc3.png)

**Comment by nikku** [comment]
Additional spike results: An improved user flow, making re-deploy the primary deploy action (https://github.com/camunda/camunda-modeler/issues/1440):

![capture INbrmt_optimized](https://user-images.githubusercontent.com/58601/69283958-c0eaf600-0bed-11ea-98a5-ced50083d552.gif)

Incorporated/explored ideas: 

* Deploy becomes a multi-button with re-deploy if configured being the primary action
* Deploy dialog may be closed, saving the entered configuration. This works if basic validation succeeds and despite the fact that the engine could not be reached at the moment => valuable input is not lost
* Modal name is adjusted to reflect main purpose => not to deploy but to configure the deployment options (if missing or if explicitly requested by user).
* Form UI does only show errors => do not scream "everything is fine" in the users face, instead: indicate if something is wrong where it is wrong. Users can be assured that things are right _unless_ explicitly indicated.
