### ISSUE TITLE
Width and Height of sequenceFlow

### ISSUE THREAD

**Issue by sylvain-seramy** [camunda/camunda-modeler#1578]
Hello

is it possible to give the ability to change the width and the height of a sequenceFlow please ?

Like a textAnnotation for example:
      <bpmndi:BPMNShape id="TextAnnotation_1p1a7pz_di" bpmnElement="TextAnnotation_1p1a7pz">
        <dc:Bounds x="4670" y="2300" width="490" height="160" />
      </bpmndi:BPMNShape>

=> 
<bpmndi:BPMNShape id="SequenceFlow_0r6c6wz_di" bpmnElement="TextAnnotation_1p1a7pz">
        <dc:Bounds x="4670" y="2300" width="490" height="160" />
      </bpmndi:BPMNShape>

Thank you

**Comment by sylvain-seramy** [comment]
damn... error of copy/paste...

<bpmndi:BPMNShape id="SequenceFlow_0r6c6wz_di" bpmnElement="SequenceFlow_0r6c6wz">
<dc:Bounds x="4670" y="2300" width="490" height="160" />
</bpmndi:BPMNShape>

**Comment by pinussilvestrus** [comment]
What do you understand about _width_ and _height_ of sequence flows?

Generally, sequence flows only can have waypoints. If you want to change the visual of a sequence flow, you will have to modify the [`BpmnRenderer`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/draw/BpmnRenderer.js#L1355) as part of a [`bpmn-js` extension](https://github.com/camunda/camunda-modeler/tree/develop/docs/plugins), which is the underlying library to render BPMN files in the Camunda Modeler.

I'll close this issue since no problem is stated inside. Please refer to [the forum](https://forum.camunda.org/) for future questions like this. Feel free to re-open if you discover an actual problem.

**Comment by sylvain-seramy** [comment]
thank you for your reply. I did not evoke the arrows but the associated text.

here is an example of replacing the text to have it on one line instead of 2.

![camunda-evol](https://user-images.githubusercontent.com/56125494/68682017-bcc33680-0564-11ea-8871-85ff24b090e2.png)

**Comment by pinussilvestrus** [comment]
When you have a look in the XML, the sequence flow has a `BPMNLabel` element, for which you can manipulate its bounds:

![image](https://user-images.githubusercontent.com/9433996/68743663-3b66b500-05f3-11ea-948d-fb6ceaf5214a.png)
