### ISSUE TITLE
Cannot use SPACE to check / uncheck check boxes in modals

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1692]
__Describe the Bug__

As a standard browser behavior pressing `SPACE` toggles the value of a checkbox.

Our space-for-handtool feature built into the app seems to interfere with this and prevent `SPACE` for toggling to work:

![capture GaQ9o7_optimized](https://user-images.githubusercontent.com/58601/74336069-e24b2080-4d9d-11ea-9e70-96c85e081639.gif)

_Imagine me pressing SPACE like crazy here._

This properly works in the properties panel (you can toggle via `SPACE` there).

__Steps to Reproduce__

* Create BPMN diagram
* Open privacy settings modal via menu
* Select checkbox
* Press `SPACE` in an attempt to toggle the checkbox via keyboard
* __See that nothing happens__

__Expected Behavior__

* With a modal dialog open, `SPACE` (like any other keyboard shortcut) is trapped inside the modal

__Environment__

- OS: Linux
- Camunda Modeler Version: v3.6.0

**Comment by barmac** [comment]
I found out that our `KeyboardBindings` stay active when the modal is open. Also, the diagram-specific shortcuts are not deregistered, which is the reason why hand tool is activated. It works fine when you open the app for the first only because by that time no editor is able to register its shortcuts.
