### ISSUE TITLE
Switching editors breaks layout

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#1702]
__Describe the Bug__

When changing to the decision table editor and switching back to DRD view, the layout got broken for the following diagram

![Kapture 2020-02-25 at 16 15 52](https://user-images.githubusercontent.com/9433996/75260599-269cde80-57ea-11ea-93b5-7afccd175db7.gif)

Note that the text annotation connection layout got broken

__Steps to Reproduce__

1. Open example diagram, cf. [diagram_1.dmn.txt](https://github.com/camunda/camunda-modeler/files/4250707/diagram_1.dmn.txt)
2. Switch to Decision Table
3. Switch back to DRD

__Expected Behavior__

The layout of text annotation got not broken

__Environment__

- OS: macOS 10.15, also discovered on Windows 10
- Camunda Modeler Version: 3.7, 3.6, 3.3

---

Depends on https://github.com/bpmn-io/dmn-js/issues/203

**Comment by nikku** [comment]
This seems to be unrelated to changing the name. Simply switching between editors does trigger the behavior. Could you double check that?

**Comment by barmac** [comment]
Sounds similar to https://github.com/camunda/camunda-modeler/issues/1679

**Comment by pinussilvestrus** [comment]
> This seems to be unrelated to changing the name. Simply switching between editors does trigger the behavior. Could you double check that?

Yes! I'll update the description

**Comment by nikku** [comment]
The actual bug has been reported a long time ago and relates to simply opening a DRD with _any_ association in it: https://github.com/bpmn-io/dmn-js/issues/203

**Comment by philippfromme** [comment]
> The actual bug has been reported a long time ago and relates to simply opening a DRD with _any_ association in it: [bpmn-io/dmn-js#203](https://github.com/bpmn-io/dmn-js/issues/203)

Not sure whether that's the exact same bug.

Using Camunda Modeler v4.0.0 I'm not able to reproduce this issue anymore by switching editors. I am however able to remove the association by replacing the decision after appending a text annotation.

![02-06-_2020_16-40-45](https://user-images.githubusercontent.com/7633572/83533462-e7201580-a4ef-11ea-9170-a019e2bf3055.gif)

The actual bug is in [`DrdRules`](https://github.com/bpmn-io/dmn-js/blob/v8.3.0/packages/dmn-js-drd/src/features/rules/DrdRules.js#L137) which only allows an association if the target is a text annotation. If the source is one, it's not allowed.

**Comment by philippfromme** [comment]
https://github.com/camunda/camunda-modeler/issues/1817 is related to that. We now create connections in the opposite direction which is why suddenly the rules disallow them.

**Comment by nikku** [comment]
https://github.com/bpmn-io/dmn-js/pull/519
