### ISSUE TITLE
Changing decision ID via properties panel results in error

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1769]
__Describe the Bug__

Changing the ID of a decision from within the properties panel / decision table view results in an error:

```
Cannot use 'in' operator to search for 'id' in undefined
```

See also screen capture demonstrating the issue:

![capture 6Rbp1F_optimized](https://user-images.githubusercontent.com/58601/78814734-6d781980-79cf-11ea-9ba5-0ac24ffc5606.gif)

__Steps to Reproduce__

1. create new DMN diagram
2. navigate to decision table
3. open properties panel (CTRL/CMD + P)
4. edit decision ID
5. see :boom: happen

__Expected Behavior__

* Decision ID can be safely edited from decision table

__Environment__

- OS: Any (tested on Linux)
- Camunda Modeler Version: v3.7.2

**Comment by pinussilvestrus** [comment]
I've tried to find the root-case for that and came out that It fails for a wrong order of events caught in the `v7.5` dmn-js version we use in this modeling version:

* It is failing because `oldProperties` are not set in the context
* [cf. `IdChangeBehavior`](https://github.com/bpmn-io/dmn-js/blob/v7.5.0/packages/dmn-js-shared/src/features/modeling/behavior/IdChangeBehavior.js#L18): we add the listener for the `element.updateProperties` and `updateProperties` listener
* [In the properties panel](https://github.com/bpmn-io/dmn-js-properties-panel/blob/v0.3.4/lib/helper/CmdHelper.js#L8), we fire the `element.updateProperties` event
* The [command which is responsible](https://github.com/bpmn-io/dmn-js/blob/v7.5.0/packages/dmn-js-decision-table/src/features/modeling/Modeling.js#L29) for setting the `oldProperties` listens for the `updateProperties` event only, which is not executed in that case (I debugged it)

We solved this problem in the current `master` while introducing the unified `element.updateProperties` event, cf. https://github.com/bpmn-io/dmn-js/commit/c5ff11fd194179e48ef7852eaf49da4a53c27b92

So backporting this "fix" to the `v3.7.x` version might be the easiest way.

**Comment by pinussilvestrus** [comment]
Got fixed in https://github.com/bpmn-io/dmn-js/tree/7.x.

Should we release a v3.7.3 version with the fix?

**Comment by nikku** [comment]
Yes + integrate. Otherwise we'll not be able to close this issue.

**Comment by oguzeroglu** [comment]
Closed via #1782
