### ISSUE TITLE
Provide Participant/Pool local Space tool

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#178]
**Use Case:** A user wants to make space inside a participant/pool only instead of the diagram.

**Solution:** Add a custom modifier that applies the space tool to the currently hovered _container element_ only.

__Demo__

![foo](https://user-images.githubusercontent.com/58601/33994050-543ef43e-e0d9-11e7-8525-2f43a59da7b2.gif)

__Context__

Related but not the same is the flow local space tool, described in https://github.com/camunda/camunda-modeler/issues/876.

---

Needs to be addressed via https://github.com/bpmn-io/bpmn-js/issues/557.

**Comment by r-dumortier** [comment]
A modifier would be great to change global space tool impact to current (over) pool.
However, I have a question, shouldn't this be the standard behavior ?

Really need that !
Thanks

**Comment by nikku** [comment]
Any ideas for the modifier key?

> However, I have a question, shouldn't this be the standard behavior ?

One use case is to create space in between participants. Any reason you see creating space on pools only as the standard behavior?

**Comment by r-dumortier** [comment]
Many thanks for your quick reply J



As Ctrl is already used a as a modifier, maybe Alt could be a good one.



I usually use the space tool in order to make space between two tasks in
the same pool.

When I have serveral pools, this modify the others pools.

In my opinion, the standard behavior should be to add space (or remove
space) only on the pool currently pointed by the mouse.

For sure, when the mouse is outside a pool, this should move all the pools



*De :* Nico Rehwaldt [mailto:notifications@github.com]
*Envoyé :* vendredi 6 janvier 2017 17:44
*À :* camunda/camunda-modeler <camunda-modeler@noreply.github.com>
*Cc :* r-dumortier <r.dumortier@moodmedia.com>; Comment <
comment@noreply.github.com>
*Objet :* Re: [camunda/camunda-modeler] Provide Participant/Pool local
Space tool (#178)



Any ideas for the modifier key?

However, I have a question, shouldn't this be the standard behavior ?

One use case is to create space in between participants. Any reason you see
creating space on pools only as the standard behavior?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/camunda/camunda-modeler/issues/178#issuecomment-270945719>,
or mute the thread

**Comment by nikku** [comment]
Good suggestion. May make sense to have the space tool contextually apply:

* when inside a pool, apply to the pool only
* when outside, apply globally

**Comment by r-dumortier** [comment]
Really happy that suits you !



J



Thanks, have a nice weekend



Raphael



*De :* Nico Rehwaldt [mailto:notifications@github.com]
*Envoyé :* vendredi 6 janvier 2017 17:56
*À :* camunda/camunda-modeler <camunda-modeler@noreply.github.com>
*Cc :* r-dumortier <r.dumortier@moodmedia.com>; Comment <
comment@noreply.github.com>
*Objet :* Re: [camunda/camunda-modeler] Provide Participant/Pool local
Space tool (#178)



Good suggestion. May make sense to have the space tool contextually apply:

   - when inside a pool, apply to the pool only
   - when outside, apply globally

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/camunda/camunda-modeler/issues/178#issuecomment-270948773>,
or mute the thread

**Comment by nikku** [comment]
Will get addressed via https://github.com/bpmn-io/bpmn-js/issues/557.

**Comment by nikku** [comment]
The space tool is local first since Camunda Modeler v5.17.0.
