### ISSUE TITLE
Zoom out DRD Overview per default

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1848]
__What should we do?__

Display DRD Overview with default zoom of 50% or 66% (whatever feels good).

__Why should we do it?__

Overview is not usable per default if we show just a bunch of elements.

**Comment by ingorichtsmeier** [comment]
What about fit to page size? 

I've seen huge diagrams with 20 or more tables where 50% didn't show everything.

**Comment by barmac** [comment]
The problem is that the element might be too small if we decide to adjust zoom to diagram size. Still, we can test that option.

**Comment by philippfromme** [comment]
> Overview is not usable per default if we show just a bunch of elements.

Is this your personal assessment or did we receive feedback regarding this?

**Comment by barmac** [comment]
This was suggested by @volkergersabeck.

**Comment by philippfromme** [comment]
So the fix is changing this line: https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/dmn/modeler/DmnModeler.js#L47

**Comment by pinussilvestrus** [comment]
Two questions which I see for this issue

1. How do we decide, what scale is the best _for every diagram_? I guess, just try out?
2. Do we really want to set the default scale [on every update](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/dmn/modeler/DmnModeler.js#L276) or only on initial import?

**Comment by philippfromme** [comment]
The overview zoom of 0.75 isn't working because the [canvas is never zoomed](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/dmn/modeler/DmnModeler.js#L276) due to a mismatch in the method name (`_handleImport` and `_handleOverviewImport`). I must have forgotten to change the method name during refactoring.

This is what a zoom of 0.75 would look like:

https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/dmn/modeler/DmnModeler.js#L276
![image](https://user-images.githubusercontent.com/7633572/86439234-7a738300-bd08-11ea-951f-6767faca2b76.png)

Zoom of 0.5:

![image](https://user-images.githubusercontent.com/7633572/86439323-aa228b00-bd08-11ea-8a90-45aaef377b1a.png)

I went for 0.75 because at 0.5 the labels are barely readable.

@volkergersabeck What do you think?

**Comment by pinussilvestrus** [comment]
The thing is, for small diagrams, 0.75 is perfectly fine, for larger diagrams maybe not. 0.5 would be otherwise than too little for smaller diagrams. How to make a decision for a fixed default scale here?

**Comment by philippfromme** [comment]
Would a diagram still be considered navigatable if you weren't able to read the labels?

**Comment by pinussilvestrus** [comment]
No, not really.

**Comment by philippfromme** [comment]
You can still zoom in and out. Maybe we should remember the zoom if the user has changed it.

**Comment by pinussilvestrus** [comment]
> Maybe we should remember the zoom if the user has changed it.

+1

**Comment by philippfromme** [comment]
Reasonable default (I'd suggest 0.75) plus remembering the zoom after the user changed it. That would leave us with the question of when and how to reset the zoom. Never? Whenever the overview is opened? When a button is clicked?

**Comment by pinussilvestrus** [comment]
We decided to fix the default zoom to 0.66 and move more advanced zoom features (like +/- buttons, saving zoom state when the user changed it and resetting to the default zoom) to another issue.

**Comment by philippfromme** [comment]
Issue regarding improved DMN overview navigation: https://github.com/camunda/camunda-modeler/issues/1857

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/9dccab5491c588324e042f4cfff912ec0d6b765d
