### ISSUE TITLE
Multiply Start Event

### ISSUE THREAD

**Issue by mendrin** [camunda/camunda-modeler#1905]
__Describe the Bug__

Hello! Why I can't use Multiple Start Event in a diagram not as a start event for a process nor as a start event for event sub process?

:
I've read "Best Practice: Avoiding Multiple Events" note, but it contradicts the Standard ;(
![Annotation 2020-08-03 225312](https://user-images.githubusercontent.com/12908957/89221732-78893200-d5dc-11ea-9e58-e2a25f53af1b.png)

**Comment by pinussilvestrus** [comment]
Can you explain what do you mean by "Multiple Start Event"?

**Comment by pinussilvestrus** [comment]
If that's the case we add support for rendering that in bpmn-js recently: https://github.com/bpmn-io/bpmn-js/commit/92bdcb83eb36d007c0c77543344797691b131f4c, but do not add support via context pad etc., only via XML.

**Comment by pinussilvestrus** [comment]
If you see good reasons for adding proper support for those elements, feel free to argue about in the forum of our [feature request template](https://github.com/camunda/camunda-modeler/issues/new?labels=enhancement&template=FEATURE_REQUEST.md).

**Comment by mendrin** [comment]
https://github.com/camunda/camunda-modeler/issues/1905#issuecomment-668613268
I mean two first elements from the picture You've provided (4 others are not start event triggers, as You know, I guess). According to the BPMN 2.0.2 Standard the process or event sub-process can have such start events, which I can't use in Camunda, as You can see from my first post:
![BPMN1](https://user-images.githubusercontent.com/12908957/89326560-27884500-d693-11ea-96e3-ce1ff8a79b80.png)
![BPMN2](https://user-images.githubusercontent.com/12908957/89326583-2fe08000-d693-11ea-82c2-7c3f5f08ab01.png)

**Comment by philippfromme** [comment]
As @pinussilvestrus already said, this is not a bug but could be considered a missing feature which doesn't necessarily mean we're going to add it. If you think this feature should be added please open a [feature request](https://github.com/camunda/camunda-modeler/issues/new?labels=enhancement&template=FEATURE_REQUEST.md).

**Comment by mendrin** [comment]
From my point of view, this should not be my request to you to modify your software product. In the end, I can choose another software solution that will not need to be modified to add any "missing feature". 
It should be your decision whether to comply with the BPMN standard or not. 
Probably, it would be fair to put in the product description that the developers interpret the standard at their own discretion and not everything that is indicated in it can be implemented using the "Camunda modeler”.

**Comment by pinussilvestrus** [comment]
> this should not be my request to you to modify your software product

The spirit of **open-source software** is in fact that we hear inside our community and take their wishes seriously. That's why we always try the approach to tackle those issues our users find the most benefit. I assume we don't have this feature because we never see a big need from our community to build it.

We don't want to create feature requests and build stuff without the knowledge whether it is really needed or not. That's why we want you as the user to give better clearance _what_ there should be built and _why_ this feature would be helpful for you, to better understand the use case.

**Comment by philippfromme** [comment]
> It should be your decision whether to comply with the BPMN standard or not.

It is our decision to adhere to the standard. Whether or not you are able to create a specific element through the UI is not an issue of adhering to the standard. Any diagram created with the Camunda Modeler is a valid BPMN diagram, any diagram that contains a multiple event can be opened with the Camunda Modeler. We simply haven't added the ability to create a multiple event through the UI because using it is discouraged and we haven't had any complaints from users wanting to use it.

Why are you missing multiple events? Did you just want to model a multiple event as you were following along the [reference](https://camunda.com/bpmn/reference/) or do you actually want to use multiple events for your processes? If that's the case you could head over to the [Camunda forum]() for advice on the subject of modeling processes without using multiple events.
