### ISSUE TITLE
incoming message flows to boundary message events

### ISSUE THREAD

**Issue by richerzhagen1978** [camunda/camunda-modeler#1919]
__Describe the Bug__

Trying to point a message flow from another pool to an attached boundary message event does not work.

__Steps to Reproduce__

1. do this
2. do that
3. now this happens
![image](https://user-images.githubusercontent.com/24294823/91276692-29b95d00-e782-11ea-9ebc-56f67cbd04bb.png)

__Expected Behavior__

My expectation is, that a connection should be feasable as I do not see that limitation in the spec (Help me, if I am wrong)

__Environment__

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]

**Comment by MaxTru** [comment]
Thanks for reporting this.

With https://github.com/bpmn-io/bpmn-js/issues/1300 boundary events as targets for message flows were disallowed.

But I agree, [BPMN 2.0 spec](https://www.omg.org/spec/BPMN/2.0/PDF) page 254, table 10.90, row 1 talks about message boundary events:
> A Message arrives from a participant and triggers the Event. If a
> Message Event is attached to the boundary of an Activity, it will change
> the normal flow into an exception flow upon being triggered.
> For a Message Event that interrupts the Activity to which it is attached,
> the boundary of the Event is solid (see upper figure on the right). Note
> that if using this notation, the attribute cancelActivity of the Activity
> to which the Event is attached is implicitly set to true.
> For a Message Event that does not interrupt the Activity to which it is
> attached, the boundary of the Event is dashed (see lower figure on the
> right). Note that if using this notation, the attribute cancelActivity of
> the Activity to which the Event is attached is implicitly set to false.
> **The actual Participant from which the Message is received can be**
> **identified by connecting the Event to a Participant using a Message Flow**
> **within the definitional Collaboration of the Process – see Table 10.1.**

According to page 44, table 7.4. this shall only be valid for intermediate boundary catch events with a message event definition. (as you stated in the title).

We will put this into the backlog! You can use this issue in order to retrieve updates about the implementation status.

**Comment by MaxTru** [comment]
Needs to be fixed in bpmn-js: https://github.com/bpmn-io/bpmn-js/issues/1346

**Comment by pinussilvestrus** [comment]
Alternative / one step further could even be to auto-morph none events to message events once connected: https://github.com/camunda/camunda-modeler/issues/914

**Comment by pinussilvestrus** [comment]
Closed via 23c40fd465a7b35af0fa608474c3638bee4c9755
