### ISSUE TITLE
Template boolean fields not persistent when binding type is `property`

### ISSUE THREAD

**Issue by aleneum** [camunda/camunda-modeler#1955]
__Describe the Bug__

In #1933, @MaxTru asked me to open a new issue concerning the behaviour of checkboxes/property attributes in camunda modeller templates. When a value of type: `Boolean` with binding type `property` is defined in a template, a checkbox will be added to the property window but it's not possible to change the value as it always resets when the element loses the scope.

As far as I understood the remarks in #1933 however, boolean support is limited. Consequentially, I am not certain this is an actual bug worth fixing.

__Steps to Reproduce__

1. Create a template file `<x>/.camunda/element-templates/templates.json`, containing this:
```
{
    "name": "Mail Task",
    "id": "com.camunda.example.MailTask",
    "appliesTo": [
        "bpmn:ServiceTask"
    ],
    "properties": [
        {
            "label": "Receivers",
            "type": "Boolean",
            "binding": {
                "type": "property",
                "name": "receivers"
            }
        }
    ]
}
```

2. Create and save an empty BPMN file in `<x>`.
3. Load BPMN file
4. Create a Service Task and assign the Element Template MailTask
5. Under Custom Fields, there will be a `receiver` checkbox which can be checked and unchecked but always resets when the ServiceTask is deselected. 

__Demo__

(open in new tab for full hd resolution)

![camunda_demo](https://user-images.githubusercontent.com/205986/94941111-bcad8b80-04d4-11eb-9bf0-6a750df3d032.gif)

__Expected Behavior__

Changes of `receiver` are persistent.

__Environment__

- OS: Windows 10 Version 2004
- Camunda Modeler Version: 4.2.0

**Comment by MaxTru** [comment]
Dear @aleneum,

thanks for reporting and the detailed description.

In the example you gave you used a property named `receivers`. But `receivers` is not a valid property for a serviceTask BPMN XML element. The Camunda modeler is a BPMN 2.0 editor built upon domain specific modeling rules (see [design principles](https://github.com/bpmn-io/design-principles#editors-not-drawing-tools)). Therefore Element Templates do not support to set a property with an invalid name according to BPMN Moddle. 

[BPMN-moddle](https://github.com/bpmn-io/bpmn-moddle) defines the BPMN meta-model, ie. what elements are valid in the context of BPMN 2.0.  

If you would use for instance the following element template you will find out that the `property` binding with `type = Boolean` does work as expected (since `camunda:asyncBefore` is a valid Camunda BPMN 2.0 XML element, see [here](https://github.com/bpmn-io/bpmn-moddle/blob/a902b7d3df929d3fa463406a7b3aa4efecfee436/test/fixtures/json/model/camunda.json#L20)). 
```json
{
    "name": "Buggy Task",
    "id": "com.camunda.example.BuggyTask",
    "appliesTo": [
        "bpmn:ServiceTask"
    ],
    "properties": [
        {
            "label": "Async Before",
            "type": "Boolean",
            "binding": {
                "type": "property",
                "name": "camunda:asyncBefore"
            }
        }
    ]
}
```

May I ask what you want to achieve? We can then support you better in finding a solution for your use case. 

For now I will close this ticket. Please also note that we are planning to implement and include a json validation of provided element template configurations to explicitly detect and highlight invalid element template configs to the user (see [here](https://github.com/camunda/camunda-modeler/issues/1939#issuecomment-698836454)).

Please don't hesitate to reach out (e.g., via forum.bpmn.io or creating another issue) in case of any more problems.

**Comment by aleneum** [comment]
Hi @MaxTru,

thank you for that detailled explanation

> May I ask what you want to achieve? We can then support you better in finding a solution for your use case.

oh, personally I was just interested in `camunda:inputParameter` and `camunda:outputParameter` which I use to communicate values to and from (Python) Service Tasks. I only tested the other binding types in #1933 for the sake of completeness. I can deal with passing everything as strings but I was looking for a way to reduce potential sources of error while creating models. Some type checking/restrictions in the modeller (String, Boolean, Int, Float, JSON, Enum: Can be done with Dropdown) could prevent spelling issue such as passing "treu" instead of "true" o "2O.1" instead of "20.1". But I am quite certain that I just scratched the surface of BPMN XML and Camunda. I still have to figure out how to do such things properly I guess.

>  Please also note that we are planning to implement and include a json validation of provided element template configurations to explicitly detect and highlight invalid element template configs to the user (see

that sounds neat

> Please don't hesitate to reach out (e.g., via forum.bpmn.io or creating another issue) in case of any more problems.

will do. thanks for the support!

**Comment by MaxTru** [comment]
Hi @aleneum ,

understand - have you looked at `constraints`? https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates#Constraints

By defining a regexp using a `constraints` configuration you could add some validation to the user inputs.

Best
Max
