### ISSUE TITLE
Remove `+` button

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#2293]
__What should we do?__

Remove the `+` button. Display the (uncloseable) empty tab with the label `Welcome` only if no other tab is opened.

![Empty tab](https://user-images.githubusercontent.com/58601/120384175-1ac19580-c326-11eb-8869-8b4cef27dbbc.png)

__Why should we do it?__

Starting with Camunda Cloud the `+` button becomes even more ambiguous. Especially given our current strict separation between execution platforms this can lead to undesired behavior for the user, cf. https://github.com/camunda/camunda-modeler/issues/2283.

**Comment by andreasgeier** [comment]
The plus button was part of the unified modeler concept but we did not find the time to implement the solution. I'm fine with removing it (at least as an intermediate fix) since this causes trouble now.

**Comment by falko** [comment]
I frequently use the `+` button in customer meetings to quickly start a new diagram of the same type for sketching something on the side.

Please consider keeping the `+` button and let it create the same type of file as the one currently open, i.e. with the same modeling language and execution platform.

When the welcome page is shown, the button can be hidden because there is already a selection for the file type.

Once a user selected a file type for the first diagram or has opened an existing file, the most likely next action is to create more of the same.

**Comment by falko** [comment]
Another option for power users if you insist on removing the `+` button would be keyboard shortcuts for all file types. But in line with my previous comment, I'd be already happy if `Ctrl + T` gives me more of the same.

**Comment by MaxTru** [comment]
> Please consider keeping the + button and let it create the same type of file as the one currently open, i.e. with the same modeling language and execution platform.

This could easily be done and I personally also favor this approach - @nikku  @andreasgeier was this dicussed, is there any reason why removing the `+` would be better?

**Comment by andreasgeier** [comment]
> > Please consider keeping the + button and let it create the same type of file as the one currently open, i.e. with the same modeling language and execution platform.
> 
> This could easily be done and I personally also favor this approach - @nikku @andreasgeier was this dicussed, is there any reason why removing the `+` would be better?

We should not do that. We also have to consider a scenario where multiple tabs are opened. Then it becomes hard to predict what file will be created. Even harder if we consider the scenario that at start up the Modeler re-opens multiple tabs from the last session.

The solution would not only violate the rule of being not predictable but also that the same button should always behave the same, meaning a plus should not create a BPMN this time and a DMN next time or (as an example from the prop panel) an error now and a message later.

**Comment by MaxTru** [comment]
I see what you mean, yet playing around with it, I do not think it is a problem. As you can see in the screencast. I dont feel it is surprising or unpredictable due to two reasons:
* the tab is always opened directly next to the currently opened tab. Therefore it is clear that a new tab of the existing one was created
* Practically, it becomes clear just by the looks of it, that I just created either a form, a DMN or a BPMN diagram
  * In case of BPMN-cloud vs BPMN-platform, I think practically a user would work either in one world or the other.

![QuickOpenNewTab](https://user-images.githubusercontent.com/42800119/121743182-3df7fc00-cb01-11eb-83e7-778133e66809.gif)

If you want to try it yourself, test with this artifact: 
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/develop/camunda-modeler-develop-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/develop/camunda-modeler-develop-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/develop/camunda-modeler-develop-mac.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/develop/camunda-modeler-develop-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/develop/camunda-modeler-develop-win-x64.zip


-----

Does this change your mind?

**Comment by nikku** [comment]
@falko @MaxTru Any change in the plus button behavior _is_ a breaking one and needs to be properly communicated to the user. Thus my proposal to simply remove it and re-consider introducing it some day in the future (or never).

If we want a _create a new document of the same type_ feature, which we do not have right now, please create a feature request for it. I do agree that is can be beneficial for quick sketches. Immediately though many other potentially useful use-cases pop up, too. What about duplicating a diagram to a new tab? Or creating a new diagram from the current selection?

My gut feeling is that we should simply remove the `+` button.

**Comment by MaxTru** [comment]
I created a new issue to evaluate the feature of *adding new property of currently opened type*: https://github.com/camunda/camunda-modeler/issues/2309

I prepared the PR which will remove the `+` button: #2308

**Comment by ingorichtsmeier** [comment]
It looks confusing as you press a button the right side of the screen, but the result appears somewhere on the left (nearly unpredictable).

But thanks for providing the video, it makes it easier to visualize and judge it.

**Comment by MaxTru** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2308
