### ISSUE TITLE
Enterprise version deploy error

### ISSUE THREAD

**Issue by Neisuz** [camunda/camunda-modeler#2322]
__Describe the Bug__
I've got created schema in camunda-modeler(4.8.1) and it works fine on platform, but i can't deploy into camunda cloud 
this schema. When i deploy the schema there is an issue

![errordeploy](https://user-images.githubusercontent.com/48782146/123015735-5a067200-d40c-11eb-80f1-71b838016186.png)

__Environment__

- OS: [e.g.linux minr]
- Camunda Modeler Version: [4.8.1]
- Execution Platform: [Camunda Cloud]

**Comment by nikku** [comment]
Hi @Neisuz! 

[HTTP 502](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502) refers to a server side error, usually because some back-end resources are not available behind a gateway. But given the error I'm not sure what is exactly going on there.

Are you able to re-deploy right now? Are you able to deploy the same diagram [via the CLI](https://docs.camunda.io/docs/product-manuals/clients/cli-client/index)? If that is the case this indicates an issue with the Camunda Modeler.

**Comment by Neisuz** [comment]
Thank for your answers.

I wanted to deploy the schema thru camunda cloud. I can deploy it with camunda modeler to tomcat-camunda server.
Feel free, try to deploy it by yourself. 
[schema.bpmn.tar.gz](https://github.com/camunda/camunda-modeler/files/6705397/schema.bpmn.tar.gz)

**Comment by MaxTru** [comment]
Thanks for the clarification Neisuz.

So what happened here:
* You created a BPMN diagram for the `Camunda Platform` product. You could successfully deploy it to a `Camunda Platform` server running locally.
* You imported it into the Cloud Modeler and tried to deploy it to a `Camunda Cloud` cluster, that failed.

This is actually expected. Please note that [`Camunda Cloud` is a new / different product](https://camunda.com/blog/2021/05/camunda-cloud-10-released/) hence deploying a `Camunda Platform` BPMN diagram to it will not work.

Please also note that the Camunda Modeler will automatically open either a `Camunda Cloud` or `Camunda Platform` specific editor based on the BPMN file provided. The Camunda Modeler would then also only offer the Deployment tool for the respective platform. Hence I am closing this issue for the Camunda Modeler.

---

Please feel free to re-open or open a new one, in case I missed anything.
