### ISSUE TITLE
Support Setting `variables` and `local` Property of `camunda:In` and `camunda:Out` Separately

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2334]
As [documented](https://github.com/camunda/camunda-modeler/tree/develop/docs/element-templates#camundain) element templates for `camunda:In` and `camunda:Out` support setting a `variables` property that will be used both for setting the `variables` and the `local` property of an element. Setting `local` to `true` without setting `variables` to `all` is not possible even though it's a valid use case and therefore should be. Furthermore, the `target` property of a `camunda:In` and the `source` property of a `camunda:Out` cannot be set at the moment.

### Example

The following is possible

```xml
<camunda:in local="true" variables="all" />
```

while the following is not possible

```xml
<camunda:out source="foo" target="bar" local="true"/>
```

### Enhancements

* [ ] allow setting `local` for specific variables
* [x] ~~allow setting `variables` independently~~
* [x] ~~allow setting `target` of `camunda:In`~~
* [x] ~~allow setting `source` of `camunda:Out`~~
* [ ] Adjust the element template json schema accordingly

---

Jira: https://jira.camunda.com/browse/SUPPORT-10964

**Comment by MaxTru** [comment]
>Furthermore, the target property of a camunda:In and the source property of a camunda:Out cannot be set at the moment.

I think this is okay, since these are the fields that I would expect the user (in the Camunda Modeler) to set. (Same as for e.g., `inputOuput`). I propose to not change that.

Regarding the design of the solution, I propose the following:

# `Camunda:in`

## Element Template Design

* (**as-is**) If `target` is set: 
`<camunda:in source="[userInput]" target="[target]"/>`

* (**as-is**) If `target` is set and `expression` is set to `true`:
`<camunda:in sourceExpression="[userInput]" target="[target]" />`

* (**as-is**) If `variables` is set to `local`:
`<camunda:in local="true" variables="all" />` (Notice there is no [userInput], therefore has to use property type of value `Hidden`)

* (:exclamation:**new**:exclamation:) If `variables` is set to `local` and `target` is set: 
`<camunda:in local="true" source="[userInput]" target="[target]" />`

* (:exclamation:**new**:exclamation:) If `variables` is set to `local`, `target` is set and `expression` is set to `true`: 
`<camunda:in local="true" sourceExpression="[userInput]" target="[target]" />`

* (**as-is**) If `variables` is set to `all`:
`<camunda:in variables="all" />` (Notice there is no [userInput], therefore has to use property type of value `Hidden`)

## Test Case / example for the new configuration option

### Example 1

```json
{
        "label": "Input source variable",
        "type": "String",
        "value": "var_local",
        "binding": {
          "type": "camunda:in",
          "target": "var_called_source",
          "variables": "local"
        }
      }
```
Results in
```xml
    <bpmn:callActivity id="Activity_00xqwbk">
      <bpmn:extensionElements>
        <camunda:in source="var_local" target="var_called_source" local="true" />
      </bpmn:extensionElements>
    </bpmn:callActivity>
```

### Example 2

```json
{
        "label": "Input source variable",
        "type": "String",
        "value": "${ asdf }",
        "binding": {
          "type": "camunda:in",
          "target": "var_called_source",
          "variables": "local",
          "expression": "true"
        }
      }
```
Results in
```xml
    <bpmn:callActivity id="Activity_00xqwbk">
      <bpmn:extensionElements>
        <camunda:in sourceExpression="${ asdf }" target="var_called_source" local="true" />
      </bpmn:extensionElements>
    </bpmn:callActivity>
```

# `Camunda:out`

## Element Template Design

* (**as-is**) If `source` is set:
`<camunda:out source="[source]" target="[userInput]" />`

* (**as-is**) If `sourceExpression` is set:
`<camunda:out sourceExpression="[sourceExpression]" target="[userInput]" />`

* (**as-is**) If `variables` is set to `all`:
`<camunda:out variables="all" />` (Notice there is no [userInput], therefore has to use property type of value Hidden)

* (:exclamation:**new**:exclamation:) If variables is set to `local` and `source` is set:
`<camunda:out local="true" source="[source]" target="[userInput]" />`

* (:exclamation:**new**:exclamation:) If variables is set to `local` and `sourceExpression` is set:
`<camunda:out local="true" sourceExpression="[sourceExpression]" target="[userInput]" />`

* (**as-is**) If variables is set to local:
`<camunda:out local="true" variables="all" />` (Notice there is no [userInput], therefore has to use property type of value `Hidden`)

## Test Case / example for the new configuration option

### Example 1

```json
      {
        "label": "Output target (source variable)",
        "type": "String",
        "value": "var_called",
        "binding": {
          "type": "camunda:out",
          "source": "var_local_source",
          "variables": "local"
        }
      }
```
results in
```xml
    <bpmn:callActivity id="Activity_00xqwbk">
      <bpmn:extensionElements>
        <camunda:out source="var_local_source" target="var_called" local="true" />
      </bpmn:extensionElements>
    </bpmn:callActivity>
```

### Example 2

```json
      {
        "label": "Output target (source variable expression)",
        "type": "String",
        "value": "var_called",
        "binding": {
          "type": "camunda:out",
          "sourceExpression": "${ asdf }",
          "variables": "local"
        }
      }
```
results in
```xml
    <bpmn:callActivity id="Activity_00xqwbk">
      <bpmn:extensionElements>
        <camunda:out sourceExpression="${ asdf }" target="var_called" local="true" />
      </bpmn:extensionElements>
    </bpmn:callActivity>
```

**Comment by philippfromme** [comment]
@MaxTru I like the proposed change as we don't have to introduce new properties. Let's go for it. 👍🏻

**Comment by nikku** [comment]
I believe this is closed via https://github.com/camunda/camunda-modeler/commit/a81fe55d1c9e3fc1768293554fae81972287b827? If not what is missing @MaxTru?

**Comment by MaxTru** [comment]
Indeed closed via https://github.com/camunda/camunda-modeler/commit/a81fe55d1c9e3fc1768293554fae81972287b827
