### ISSUE TITLE
Regression with deployment in version 4.8.0 to camunda version 7.8.0

### ISSUE THREAD

**Issue by michaelarnauts** [camunda/camunda-modeler#2340]
__Describe the Bug__

After upgrading from modeller 4.7.0 to 4.8.0, it's not possible to do deployments from the modeller anymore.

I'm quite sure it's due to the `/engine-rest/version` call that is being made now, but that endpoint isn't available on camunda version (7.8.0). I can see that modeller 4.8.0 is trying to call that endpoint, but it returns a 404.

__Steps to Reproduce__

1. use camunda modeller 4.8.0
2. use camunda 7.8.0
3. try deployment
4. nothing happens (not even an error message)

__Expected Behavior__

deploy

__Environment__

- OS: Ubuntu
- Camunda Modeler Version: 4.8.0
- Execution Platform: Camunda Platform
- Installed plug-ins: N/A

**Comment by barmac** [comment]
I was able to reproduce this issue locally. Thank you for reporting.

The problem is within [the DeploymentTool](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js#L138). We try to retrieve the version and when the call fails, deployment is aborted. So to fix this, we could make sure that the deployment continues even if we cannot detect the version.

**Comment by barmac** [comment]
As Camunda Platform 7.8.0 is out of support, we are rather not prioritising this issue. Still, feel free to implement a fix. We will happily accept a pull request.
