### ISSUE TITLE
Reintroduce buttons in top toolbar

### ISSUE THREAD

**Issue by jtvilm** [camunda/camunda-modeler#2376]
Compared to version 4.8.1, in version 4.9.0 the buttons related to file actions, such as open, save, and save as, as well as the undo/redo buttons were removed. 

Why? From your perspective, what are the benefits for users not having these items easily accessible?

In my opinion the usability suffers, now that one needs to constantly use the file menu items to open a bmpn or dmn file in the last used folder, for example.

If there are good reasons to remove the buttons by default, please make the toolbar at least configurable, so that users can readd them as they deem necessary.

Otherwise, please revert to the previous top toolbar where open, save, save as, and undo redo buttons where available.

Thank you!

**Comment by nikku** [comment]
What you're seeing shipped with v4.9 is the first step towards a toolbar-less modeler and I'm happy you share your feedback here.

Could you use the [bug report template](https://github.com/camunda/camunda-modeler/issues/new?assignees=&labels=bug&template=BUG_REPORT.md) and add a little bit more context? Especially the details regarding your operation system would be interesting.

As a follow up question, are you aware of the keyboard shortcuts for all these actions?

**Comment by nikku** [comment]
Are you aware of the keyboard shortcuts for all these actions?

**Comment by nikku** [comment]
Any chance to follow up on my question?

**Comment by jftsaraiva** [comment]
I added a post in [Camunda Forum](https://forum.camunda.org/t/missing-load-and-save-buttons/29549) before see this issue because after some days working with 4.9.0 I still need buttons back :-D 

> Are you aware of the keyboard shortcuts for all these actions?

Yes, but it isn't the same thing. 

> The benefit once the toolbar is gone entirely is that you as the user will have additional space to do the actual work.

Personally I prefer to have the toolbar with the tools I use more than additional space to do the actual work

**Comment by RicardoLieblein** [comment]
Maybe you could make the toolbar optionally toggleable?

**Comment by andreasgeier** [comment]
Thank you for your feedback.

Which OS do you use? Under Linux and Windows, these actions are just 20px away in the app menu if you don't like keyboard shortcuts.

As nikku already mentioned we are planning to move the Modeler towards a modeling IDE with a lean UI and exciting new features for developers. If you look at other IDEs such as VSCode, Atom, etc. you won't find space-consuming toolbars with standard actions like open, save, undo etc.

We hope this will be appreciated by our users and we will carefully listen to all voices over the next months to understand how well this and upcoming changes will be received.

**Comment by nikku** [comment]
Thanks for jumping in @andreasgeier.

I'll close this issue as `wontfix` for the moment. We'll carefully listen to further feedback.

**Comment by vdenisov** [comment]
This is a terrible decision. The save button not only was the fastest mouse-based way to save a file, but also a quick indicator if the file was modified at all (which was very helpful when reconciling version tags at the end of the editing session). Please consider making the toolbars toggleable instead of simply removing existing functionality, this will satisfy everyone.
