### ISSUE TITLE
Add menu entry for "recently opened files"

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2504]
__Is your feature request related to a problem? Please describe.__

Use-case: We create our process models with the program „Camunda Modeler“. Oftentimes, we work on several projects at the same time, which are located in different folders on the computer.

As of now, it’s a bit cumbersome to open the process models in the Modeler because it does not have the menu entry for “open recently opened files”. Sure, it’s possible to open the models via the IDE. But there are cases where we work mostly on the models and hence primarily with the Modeler.

__Describe the solution you'd like__

Add a menue entry to the file menue which allows to view and open "recently opened files".

__Describe alternatives you've considered__

n/a

__Additional context__

[SUPPORT-8641](https://jira.camunda.com/browse/SUPPORT-8641)

**Comment by MaxTru** [comment]
Moving to backlog since requirement seems clear to me.

**Comment by andreasgeier** [comment]
There are already solutions available for this request.

(1) Recent files as part of the "plus" button, see [prototype v14](https://fluffy-fiesta-212e1c7c.pages.github.io/prototypes/visual-ide/v14/):

<img width="439" alt="Screen Shot 2021-11-04 at 1 28 50" src="https://user-images.githubusercontent.com/938244/140321665-992c5415-172d-4daf-8436-47e624c5c460.png">

(2) Recent files listed on the welcome tab, see [prototype v14](https://fluffy-fiesta-212e1c7c.pages.github.io/prototypes/visual-ide/v14/):

<img width="1079" alt="Screen Shot 2021-11-04 at 14 30 17" src="https://user-images.githubusercontent.com/938244/140321914-e0a4ba64-236f-46c7-ac05-01198ed9a9c8.png">

Solution (1) is preferred since it is always accessible and not part of just one specific view. In addition, such a list should also be part of the app menu.

**Comment by nikku** [comment]
Good catch, we overlooked this one.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/issues/3917.
