### ISSUE TITLE
Editors retrieve the latest version of the engine defined in template diagram file 

### ISSUE THREAD

**Issue by smbea** [camunda/camunda-modeler#2545]
__What should we do?__

**Context:** When creating a new diagram/form, the initial template file uses a hardcoded `executionPlatformVersion` -> implies manually changing the version in each template file every time a new version is added.

**->** We should check for the latest supported version of the engine when creating a new editor.

__Why should we do it?__

When a new engine version is added, it will automatically become the default version.
* less time consuming
* less prone to outdated versions

**Comment by nikku** [comment]
How does this issue relate to https://github.com/camunda/camunda-modeler/issues/2491? Is this a duplicate?

In an ideal world we simply use the last version a user selected. I'd not assume as a user that I am always on _latest_. Instead, if my setup forces me to be on legacy Cloud 1.0, I want to stay on Cloud 1.0 for the next diagram, too.

**Comment by MaxTru** [comment]
I would see it as following:

This issue here implements the default. I.e. if no *what did the user select the last time* information exists and I just create a blank new file, then the latest version should be added. This affects:

- [ ] https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/form/initial.form#L5
- [ ] https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/form/initial-cloud.form#L5
- [ ] (Maybe, if we have that info for BPMN [I assume we only have this, once we implemneted linting?]) https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/bpmn/diagram.bpmn#L2

On top I think, #2491 would implement a logic, that the *last version used* is stored and used when creating a new file.

WDYT?

**Comment by nikku** [comment]
Agreed. 

Personal opinion: If the implementation is a straight forward one that makes sense. If it is complex, I'd rather invest time into https://github.com/camunda/camunda-modeler/issues/2491. From my point of view https://github.com/camunda/camunda-modeler/issues/2491 is the one with bigger user impact.

**Comment by nikku** [comment]
Closing this in favor of https://github.com/camunda/camunda-modeler/issues/2491.
