### ISSUE TITLE
Align most prominent background colors for Modeler 5

### ISSUE THREAD

**Issue by andreasgeier** [camunda/camunda-modeler#2671]
__What should we do?__

With the new properties panel for DMN and Forms, soon we have the most prominent parts of the UI in line with the new color palette of the Desktop Modeler. Two areas are still standing out: 

- the BPMN+DMN+Form palette background
- the DRD overview on decision table editing.

__Why should we do it?__

We should align these backgrounds to have the new color schema in place for the most prominent areas of the UI. Technically, we can leave the libraries untouched and simply overrule the CSS variables in the Modeler.

Expected grey: `hsl(225, 10%, 97%)`

Result of diagram palette change:

![Screen Shot 2022-01-13 at 11 13 05](https://user-images.githubusercontent.com/938244/149311359-c18e1dfc-9ac6-4c9d-8e1e-b8c6a5d7d854.png)

Result of form palette change:

![Screen Shot 2022-01-13 at 11 13 08](https://user-images.githubusercontent.com/938244/149311410-d32d2fe6-72f9-4f68-9cf7-e5a9afc1518b.png)

Result of the DRD overview change (please note, that the change is barely noticable here but since this is dependent on Monitor settings and quality, I would suggest to do it anyway, just to be sure):

![Screen Shot 2022-01-13 at 11 23 54](https://user-images.githubusercontent.com/938244/149312364-d95ac43a-8b51-4dc5-9d5b-30f7beb8810d.png)

**Comment by andreasgeier** [comment]
I suggest considering this for the Modeler 5 major release.

**Comment by pinussilvestrus** [comment]
Regarding the palette, I think we already aligned these colors in the upstream libraries when doing the general color updates (https://github.com/camunda/camunda-modeler/issues/2459)
* https://github.com/bpmn-io/diagram-js/issues/581
* https://github.com/bpmn-io/form-js/issues/192

We probably didn't release and integrated these changes, yet. That's why it's not in the nightly. It's different for the decision overview, this has to be updated [in this project](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/dmn/OverviewContainer.less#L5)

**Comment by nikku** [comment]
Closing this as won't fix. If we decide to prioritize such thing, let's re-open some day maybe or create a new issue.
