### ISSUE TITLE
Copy the error message into the clipboard

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#2687]
__Is your feature request related to a problem? Please describe.__

If I get an error message in the modeler, I would like to copy the message 
![grafik](https://user-images.githubusercontent.com/7870843/149928452-6988f2b1-a382-4585-bcab-05c8c711c6a0.png)

Right now, the content is disabled and I could not mark it with my mouse to copy it.

__Describe the solution you'd like__

In the Error log, I would like to mark the message or parts of it with my mouse and copy it to the clipboard.

__Describe alternatives you've considered__

Nothing. Retyping is horrible.

__Additional context__

## Camunda Modeler system information
 * Version: 4.13.0-nightly.20220116
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Cloud

**Comment by philippfromme** [comment]
This is due to a `* { user-select: none: }` rule that we added to prevent the user from accidentally selecting text anywhere in the application. For log we manually enabled selecting and copying because it makes sense. We should do the same for linting errors. Ideally the user would only have to click the error message to copy it to the clipboard. 🤔

**Comment by ingorichtsmeier** [comment]
Reopening as it doesn't work on version 5.14.0.

I cannot mark the error message to copy it into my clipboard.

**Comment by philippfromme** [comment]
This is caused by focusing the properties panel on clicking the error message, a feature we introduced after fixing this issue. It doesn't happen when the properties panel isn't focused (e.g. undefined task not supported):

![Camunda_Modeler_EeV3rcuqFm](https://github.com/camunda/camunda-modeler/assets/7633572/e479db09-46a9-44b7-afb2-12a308be4776)

We could fix this by either copying the error message by default on click or offering a dedicated button or something similar to copy like there is in the _Output_ tab.

![image](https://github.com/camunda/camunda-modeler/assets/7633572/3aac1063-a5b5-4774-9772-7773d900a8d7)

Thoughts @nikku?

**Comment by nikku** [comment]
I think we should investigate how to distinguish text selection from click. As a user I expect selection to happen _or_ click to focus the error.
