### ISSUE TITLE
Modeler loses the active tab indicator

### ISSUE THREAD

**Issue by andreasgeier** [camunda/camunda-modeler#2732]
__Describe the Bug__

With recent Nightlies of the Modeler and also with the Modeler 5.0.0-alpha version, the active tab indicator for the opened editor (the dark grey line) gets lost from time to time.

__Steps to Reproduce__

Did not yet find out how to reproduce.

Here is a screenshot:

![Screen Shot 2022-02-08 at 15 56 14](https://user-images.githubusercontent.com/938244/153012768-61cdb83e-86f4-461c-8449-7141f2bf1106.png)

__Expected Behavior__

The active tab indicator should remain.

__Environment__

 * Version: 5.0.0-nightly.20220202, Camunda Modeler Version: 5.0.0-alpha.1
 * Operating System: Mac OS 12.1.0 
 * Plugins: Cloud Connect
 * Execution Platform: BPMN - Camunda Platform

**Comment by philippfromme** [comment]
@marstamm Thanks for looking into this. We'll find a solution.

**Comment by marstamm** [comment]
# Root cause

We register and unregister the callback here:
https://github.com/camunda/camunda-modeler/blob/1703073e6419fbb388b8721db2072eb5c6e9272a/client/src/app/tabs/bpmn/BpmnEditor.js#L217

`fn` can either be `on` or `off`. However, because `viewer.off` does not expect a priority.

https://github.com/bpmn-io/bpmn-js/blob/069b1902c988fbff1ef754f14657242639161cc1/lib/BaseViewer.js#L568

Therefore, we never unregister the callback. After changing Tabs, it is executed twice. Some async callbacks later, and the double update seems to be too much for react state.

Solution steps: 
  1. properly use the existing API
  2. make the bpmn-js API more resilient against this (e.g. `viewer.off` can accept priority, even if it is not needed)
