### ISSUE TITLE
Save space avoiding unnessessary scroll bar

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#2831]
__What should we do?__

In the property panel, a scroll bar appears, although there is space at the bottom of the panel:

![grafik](https://user-images.githubusercontent.com/7870843/159665122-b8a0fd34-5683-4910-bcee-d348ec75da96.png)

There is empty space below the section 'Tasklist', but a scrollbar is shown.

__Why should we do it?__

As one argument to get rid of the tool bar was to save space, you could save space on the side as well.

**Comment by smbea** [comment]
Thank you for your report. I could reproduce this on my machine by reducing the window size.

This is caused by a padding added here https://github.com/bpmn-io/properties-panel/blob/30d7db53ccdc892c86cb3988f99ed7e97e5779d9/assets/properties-panel.css#L195. I don't see a reason why this can't be removed or at least decreased significantly (cc @andreasgeier )

**Comment by andreasgeier** [comment]
When this padding only affects the scroll container we should remove it. I don't see a reason for it, too. The [prototype](https://fluffy-fiesta-212e1c7c.pages.github.io/prototypes/visual-ide/v14/) has padding:0;

**Comment by smbea** [comment]
Fixed upstream via https://github.com/bpmn-io/properties-panel/pull/145
