### ISSUE TITLE
Improve selection of a pool

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#2859]
__Is your feature request related to a problem? Please describe.__

As a user I wan to model properties for elements that I click on the diagram. This works well and intuitive for tasks and connections, but does not work for container elements such as participants and sub-processes:

![capture 20MKr7_optimized](https://user-images.githubusercontent.com/58601/166200380-db584eb4-41d5-4190-b578-38a88f5a5de0.gif)

If I click into a pool only selects the Collaboration properties. But it is much more important to access the elements of the Participant (name, history cleanup, candidate starter, ...)  

__Describe the solution you'd like__

* Clicking into a container element selects it
* Dragging a container element (outside the drag area) _still does not drag it (but drags the canvas instead)_

__Describe alternatives you've considered__

None.

__Additional context__

When I model my process diagram in a pool, I have to select the begin of the pool to access the properties of the process in the properties panel.

In larger diagrams, it makes it very tedious. Scroll to the beginning, ...

The selection of the Collaboration is much less important for a developer.

**Comment by pinussilvestrus** [comment]
I think it was a conscious decision to [make pools only selectable on their borders](https://github.com/camunda/camunda-modeler/issues/238), to make it easier to navigate inside. This was introduced with [Modeler Version 3.3](https://camunda.com/blog/2019/08/camunda-modeler-3-3-released/)

![Kapture 2022-03-31 at 11 11 27](https://user-images.githubusercontent.com/9433996/161020606-e8db5e65-41e9-4061-9482-c471d768b143.gif)

Since the selection of an element is the same as the selection in the properties panel, the collaboration will always be shown if the process itself is not selected on its borders.

**Comment by ingorichtsmeier** [comment]
Hi, after getting back to Modeler 4.12 I saw it's the same behavior here.

@nikku: It's a task to consider. Not a bug, maybe a feature request. I've edited my initial post that I was wondering only about the displayed properties.

I was working with a larger diagram with multiple pools, but I can't remember which one. 

My task was to change the proprties of the pools. (e.g. historyTimeToLive) 

The current behavior to move the canvas by a selection in the pool is fine and should be kept. I was wondering, why not show the properties of the pool instead of the properties of the collaboration.

**Comment by nikku** [comment]
I can see your point "can we improve it"? I don't see it as a task, but a feature request though.

And I'd ask you to provide further details: If the current move interaction is fine and should be kept, what selection interaction would help remedy your issue? Consider a process with more than one participant.

**Comment by ingorichtsmeier** [comment]
It would be nice if the property panel shows the properties of the selected pool instead of the properties of the collaboration: 
![grafik](https://user-images.githubusercontent.com/7870843/161578099-0c466522-6379-4a66-8b92-3c676ccbd2f4.png)

And show the collaboration properties only if I click somewhere outside a pool.

**Comment by smbea** [comment]
Since discussion on this topic is still ongoing, I will move it to backlog keeping the "help wanted" label.

**Comment by nikku** [comment]
Verified with @ingorichtsmeier that this is a UX issue. We should investigate if we're able to separate click to select (for containers) from drag start. This way we'd be able to support this without breaking the existing move interaction.

**Comment by barmac** [comment]
I am going to look into this this week. If I can't fix it, I'll share my findings.

**Comment by barmac** [comment]
I am sharing here my findings so far:
* For "frame" elements like Participant and Group, we use CSS property `pointer-events` to decide which parts of the shape are interactive. 
* Because we use `pointer-events: stroke` for the body of both of the shapes, it is transparent to the browser regarding mouse/touch interaction.

Solution sketch:
* Use `pointer-events: all` for the frame shapes.
* Decide in the application layer whether and how to react on the interaction.
* Ideally, the hit boxes should allow either both dragging and click interactions or only the clicks.

**Comment by barmac** [comment]
Another, more detailed solution sketch:

* Introduce `djs-hit-click-only` type which accepts all pointer events
* However, when this new type is activated, check the element type:
  * For click-like events, handle the event as with other hit boxes.
  * For other events, handle the event with target overwritten to the first non-`djs-hit-click-only` hit taken from `document.elementsFromPoint`.

This may degrade the performance, so let's be careful.

**Comment by barmac** [comment]
Alternative (limited) solution:
Instead of using `document.elementsFromPoint`, always fall back to the canvas. The rest is the same.

**Comment by barmac** [comment]
> Another idea: Have hit boxes which don't allow dragging. Build the functionality in the dragging module so that it can decide whether dragging should be activated for the hit box.
> 
> Edit: This should be rather implemented in the Move module.

I ended up implementing this solution but the new hit box type disables only the element movement feature. As a result, we don't mess with events or `document.elementsFromPoint`, but still achieve the desired selectable Participant/SubProcess/Lane.

**Comment by barmac** [comment]
This is fixed upstream via https://github.com/bpmn-io/bpmn-js/pull/1646

**Comment by Skaiir** [comment]
Close via e77fc5da94aeb224de1f813b4c936558385be96f
