### ISSUE TITLE
Absence Request Sample Does Not Deploy

### ISSUE THREAD

**Issue by dknapp47** [camunda/camunda-modeler#2975]
### Describe the bug

The Absence Request sample process has conditional expressions like this:

= return = "needsClarification"

Deploying that to Zeebe results in an error:

- Element: Flow_1f7d78d > conditionExpression
    - ERROR: failed to parse expression ' return = "needsClarification"': Expected (ifOp | forOp | quantifiedOp | disjunction):1:2, found "return = \""
- Element: Flow_1a3eadh > conditionExpression
    - ERROR: failed to parse expression ' return = "rejected"': Expected (ifOp | forOp | quantifiedOp | disjunction):1:2, found "return = \""
- Element: Flow_12c4qv2 > conditionExpression
    - ERROR: failed to parse expression ' return = "approved"': Expected (ifOp | forOp | quantifiedOp | disjunction):1:2, found "return = \""

It appears that "return" is a reserved word. Changing the process variable to "result" avoids the issue.

### Steps to reproduce

1. In the web modeler, create a bpmn diagram from the Absence Request template
2. Download it
3. Deploy it to Zeebe

### Expected behavior

A bpmn model created from a sample should deploy succesfully.

### Environment

- OS: MacOS 10.15.7
- Camunda Modeler Version: Web Modeler
- Execution Platform: Zeebe 8.0.2

**Comment by pinussilvestrus** [comment]
Thanks for your request! It seems like your issue is related to the Web Modeler application. This project here is about the Desktop Modeler, so you likely won't find help here to fix your issue.

As there is currently no dedicated open feedback channel for the Web Modeler, I'd recommend submitting your issue in the [Camunda Forum](https://forum.camunda.io/). 👍
