### ISSUE TITLE
Element Template for Connector

### ISSUE THREAD

**Issue by saig0** [camunda/camunda-modeler#308]
As Dev, I want to create an element template for a service task which is implemented as connector (i.e. Implementation = Connector). Regarding this, I need to bind a string to 'camunda:connectorId'. Additionally, I want to specify the input/output mapping for the connector. 

``` xml
<bpmn:serviceTask id="connector-1" camunda:modelerTemplate="connector-template">
      <bpmn:extensionElements>
        <camunda:connector>
          <camunda:inputOutput>
            <camunda:inputParameter name="in">in</camunda:inputParameter>
            <camunda:outputParameter name="out">out</camunda:outputParameter>
          </camunda:inputOutput>
          <camunda:connectorId>connector-id</camunda:connectorId>
        </camunda:connector>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
```

**Comment by StephenOTT** [comment]
Is this possible with current property bindings?

**Comment by StephenOTT** [comment]
@nikku do you see any blockers for this feature?  We are looking at adding some resources to do a PR, but just wanted to check if you foresee a blockers ?

**Comment by nikku** [comment]
Nope, no blockers. Let's just discuss the specifics (what you'd actually like to template, what should be editable by the modeling user / citizen developer) before you start working on the PR.

**Comment by StephenOTT** [comment]
Sure.

So easy use case:  `http-connector`

Connector's ID and its Input and Output mappings:
So that instead of having to manually populate such as the following, we can use a template.

![screen shot 2017-01-27 at 4 27 04 pm](https://cloud.githubusercontent.com/assets/1994838/22388236/9b581428-e4ad-11e6-8078-14fe15ab5ce6.png)

So using the template would configure the http-connector for the user based on the specific template.

Similar to the Mail Template example, additional template fields could be used to populate input variables for specific configurations that the user is making. Example: A http-connector to look up the weather in a City, and the template field allows to type a City's Name, vs another template what uses the same web service but is configured to look up the weather for all cities in a provided country.

**Comment by StephenOTT** [comment]
@nikku thoughts on this?

**Comment by nikku** [comment]
Sorry for the late response.

No additional thoughts. Exactly what we'd like to see, too.

**Comment by StephenOTT** [comment]
@nikku 

are you good with a format such as this:

```json
[
  {
    "name": "Http-Connector Test",
    "id": "http-connector-test1",
    "appliesTo": [
      "bpmn:ServiceTask"
    ],
    "properties":[
      {
        "label": "My URL",
        "description": "My URL",
        "type": "String",
        "binding": {
          "type": "camunda:inputParameter",
          "name": "myURL"
        }
      }
      ],
    "scope":[
      {
        "scope": "camunda:connector",
        "properties":
          [
            {
              "label": "Implementation Type",
              "type": "String",
              "editable": false,
              "binding": {
                "type": "cammunda:conector",
                "name": "http-connector"
              }
            },
            {
              "label": "url",
              "type": "String",
              "value": "httpMyUrl",
              "binding": {
                "type": "camunda:inputParameter",
                "name": "url"
              }
            }
          ]
      },
    ]
  }
]
```

Where we introduce a "scope" array that controls where the properties are placed.

**Comment by nikku** [comment]
Any rational behind `scope`? Could it be used to customize event definitions in the future, too?

**Comment by StephenOTT** [comment]
@nikku the scope was added because of the re-use of some of the xml elements such as `camunda:inputParameter`.  We needed a way to tell

```
            {
              "label": "url",
              "type": "String",
              "value": "httpMyUrl",
              "binding": {
                "type": "camunda:inputParameter",
                "name": "url"
              }
```

to be part of the Connector's Input/Output mappings and not the Activity's/tasks Input/Output mappings.

Can you give me some more info about the event definitions?

**Comment by GuillaumeSmaha** [comment]
@nikku I try to develop the example given by @StephenOTT but I have some difficults to do this because my new elements (connectorId, inputParameter in the scope elements) are created as `ModdleElement` inside the `values` array instead of an attribute in the connector.
See the screenshot :
![camunda_template](https://cloud.githubusercontent.com/assets/1287922/24555351/d58a11a0-15fe-11e7-8da9-4f96000817b0.png)

And here the function which read the scope elements :
https://github.com/GuillaumeSmaha/bpmn-js-properties-panel/blob/feature/add_scopes_snapshot/lib/provider/camunda/element-templates/cmd/ChangeElementTemplateHandler.js#L204
https://github.com/GuillaumeSmaha/bpmn-js-properties-panel/blob/feature/add_scopes_snapshot/lib/provider/camunda/element-templates/cmd/ChangeElementTemplateHandler.js#L133

Should I try to continue in this way ? or should I create types like `camunda:connector`, `camunda:connectorInputParameter` and `camunda:connectorOutputParameter` ?

**Comment by nikku** [comment]
@StephenOTT There is certain Camunda extensions such as [`class`](https://docs.camunda.org/manual/7.6/reference/bpmn20/custom-extensions/extension-attributes/#class) that can be put on nested children, such as `MessageEventDefinition`. Your proposal seems versatile to support assigning these in the future, too.

**Comment by nikku** [comment]
@GuillaumeSmaha looks good so far.

A few additional things to keep in mind:

* The host element (connector) must be created via the command stack, too so that connector assignments are undoable.
* We have extensive validation for element template JSON implace. With the scope implementation, you'd need to add quite a number of additional checks, too.

**Comment by nikku** [comment]
I've added one additional [implementation notice](https://github.com/bpmn-io/bpmn-js-properties-panel/commit/0d7ba549b78c5f1c4a1634b005a7774719ada59f#comments).

**Comment by nikku** [comment]
@GuillaumeSmaha Do you mind filing a PR already? Makes it easier to discuss implementation related stuff.

**Comment by StephenOTT** [comment]
cross-reference: https://github.com/bpmn-io/bpmn-js-properties-panel/pull/229

**Comment by StephenOTT** [comment]
@nikku before we move forward on this any further, can you and the team provide some feedback on the PRs. 

Thanks!

**Comment by StephenOTT** [comment]
@nikku any further comment you can provide?

Thanks

**Comment by nikku** [comment]
Will have a look at it this week.

**Comment by StephenOTT** [comment]
@nikku

**Comment by nikku** [comment]
Added [review hints](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/229).

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/229.

**Comment by StephenOTT** [comment]
@GuillaumeSmaha Great work! 🎉 

@nikku would the new feature be in the nightly of Camunda Modeler?

**Comment by nikku** [comment]
Yes, starting from tonight :wink:.
