### ISSUE TITLE
ooops, this should not have happened. This tab crashed due to an unexpected error

### ISSUE THREAD

**Issue by Telesforo1969** [camunda/camunda-modeler#3141]
### Describe the bug

I can not open Camunda Modeler

### Steps to reproduce

1.- I Copy downloaded plugins from version 4.12
2.- I paid in the new folder resources > plugins
3. Open Camunda modeler
4. The error was presented. (Title ). 
5. I can not open Camunda Modeler

### Expected behavior

I could modeler process 

### Environment

- OS: [e.g. MacOS 10.2, Windows 10 Pro]
- Camunda Modeler Version: [e.g.5.3.0.0 ]
- Installed plug-ins: [...]
![List Plugins](https://user-images.githubusercontent.com/92832047/190452699-6fd865d5-5047-4a54-8c67-7f3d9fd99b82.JPG)

**Comment by nikku** [comment]
@Telesforo1969 Thanks for opening this issue.

As the major version bump suggests [5.0 is not a drop-in replacement](https://github.com/camunda/camunda-modeler/blob/develop/CHANGELOG.md#500) for 4.12. I suggest to check the installed plug-ins to see if some need an upgrade.

In order to get detailed assistance please not only share the error message but the _FULL_ error that appears. It usually sheds a light on the root cause of an issue.
