### ISSUE TITLE
Overflowing long prefix and suffix values in the form fields

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3381]
### Describe the bug

When we add a long prefix and suffix values to any form element we could see it overflowing from the sides  

### Steps to reproduce

1. Create a new form
2. Add any form element say Text field
3. Add quite a long text for prefix and suffix 
4. We could see that the text is overflowing from the sides of the field
<img width="736" alt="51e9d2df22a76416a4edefa3776bd327" src="https://user-images.githubusercontent.com/85225325/211037358-2a1e7ad0-3443-43d2-8f66-4a17493223e5.png">

### Expected behavior

We could either make use of ellipsis here or restrict the number of characters for prefix/suffix 

### Environment

- OS: [ Windows 10]
- Camunda Modeler Version: [5.7.0 rc-1]
- Execution Platform: [Camunda Cloud]

**Comment by Skaiir** [comment]
For now as a fix to this we have decided to simply truncate the text as we consider most scenarios of overflow as a misuse of the adorners in the first place, the PR for this is [here](https://github.com/bpmn-io/form-js/commit/8be8c08a97988046444807e928cb38db59a078d7). 

As alternatives, we have considered restricting the width of the adorners and also restricting the length of the adorner text but since this is a problem that is very dependent on the viewport, we decided to leave users the freedom to write text that doesn't fit, as it is an edge case. In any case we'll truncate to keep it visually sensible, especially in the editor which has a pretty narrow viewport preview mode.

**Comment by Skaiir** [comment]
[Slack conversation around this](https://camunda.slack.com/archives/C046XS3GGCR/p1673269224513349)

**Comment by pinussilvestrus** [comment]
Fixed upstream via https://github.com/bpmn-io/form-js/pull/489

**Comment by Skaiir** [comment]
@nikku As the guy who provided this exact fix me too :trollface:. 

Is it turning into multi-line in the modeler integration then?

**Comment by nikku** [comment]
Not sure. Just reporting from a users standpoint. :see_no_evil:

**Comment by Skaiir** [comment]
Ah I see what's wrong, good find, some CSS changes clashed.
