### ISSUE TITLE
Restrict number formats in fields "decimal" and "increment" for a number form element

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/camunda-modeler#3382]
### Describe the bug

When we choose a number form element we could see that there are options in the properties panel to restrict the number of decimal places and increment the value of the number.

For restricting the number of decimal places we could enter a decimal number but does not really make sense to restrict the digits using a decimal number

Also in case of increments when we enter "0 "as an increment error is thrown but when we add any other number next to it we could see that the enter number is taken into account along with the 0 entered before say 05.
"0" before the number should not be accepted as it leads to confusion

### Steps to reproduce

1. Create a form
2. Add a number field
3. in the properties panel add the following 
decimal digits -> 5.123
Increment->0005
4. We could see that the decimals in decimal digit field and the "0" in front of the number in the increment field is ignored
<img width="209" alt="74b14978fcaab5a7ef7f1a665265b65e" src="https://user-images.githubusercontent.com/85225325/211039712-991f248b-5999-46f9-8a42-56fdff2a433d.png">

### Expected behavior

To avoid ambiguity to users the above fields must be restricted to valid number formats 

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by Skaiir** [comment]
Regarding the increment, this is something I've overlooked but I have a fix ready in the next version of form-js. 

Regarding decimal digits, it's more of a limitation/slight bug of the number field in the properties panel. This can be replicated with any other simple number field. May be worth raising within the properties panel.

**Comment by Skaiir** [comment]
Partially fixed upstream via https://github.com/bpmn-io/form-js/pull/490. We now trim the increment value to strip it of prefixed zeros.

Regarding the `decimal digits` property, this is just a limitation of the properties panel at the moment, there is validation but it's the default browser one which isn't super obvious to tell (you can see it by hovering on the field). I've raised a request for improvement [here](https://github.com/bpmn-io/properties-panel/issues/206), which I am happy to provide a PR for as well, provided someone in the bpmn.io team considers it a valuable improvement. Otherwise unfortunately I cannot do much about it besides switching over to a text field to handle the validation, but this would have the downside of losing us the increment arrows.

**Comment by pinussilvestrus** [comment]
@Skaiir I added the HTO iteration 16 milestone to https://github.com/bpmn-io/form-js/pull/531 so we do not swallow our calculation and the Desktop Modeler team can modify the milestone on this issue 👍

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/3422.
