### ISSUE TITLE
Point to a troubleshooting page in our docs on deployment errors

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-modeler#3468]
### Problem you would like to solve

Deployments can fail due to a variety of reasons. However, wo do not point to a place where users can inform themselves on how to recover from (common) problems.
For example, customers hosting the Zeebe Gateway on https with custom certificates need to point to those certificates when deploying from Desktop Modeler, or add the certs to their trust stores. If they deploy without it, Modeler does not hint the user on how this can be fixed. They need to read the documentation upfront:

- https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/flags/#zeebe-ssl-certificate

However, the deployment documentation doesn't point to it either: https://docs.camunda.io/docs/next/self-managed/modeler/desktop-modeler/deploy-to-self-managed/

### Proposed solution

* Point to a troubleshooting page in our docs on deployment errors. This page should include the problem of missing SSH certificates, and how to configure them.
* Change the warning "should point to running zeebe instance" to "Cannot connect to running zeebe instance"

### Additional context

Cf. https://jira.camunda.com/browse/SUPPORT-15806

**Comment by nikku** [comment]
> Point to it only when deployment fails due to missing certificate

We cannot do this as we cannot distinguish between "connection failed due to TLS connection issue" and "conenction failed due to network being unavailable". This is an infrastructure issue.

----

I propose that we rather improve our self-managed documentation to clearly feature "custom certificates". The deploy dialog does not sound like the right place to configure this.

One improvement that we could add is to change "should point to running zeebe instance" to "Cannot connect to running zeebe instance", which is closer to the truth in case of SSL certificate issues.

**Comment by christian-konrad** [comment]
> we could add is to change "should point to running zeebe instance" to "Cannot connect to running zeebe instance"
+1

> Maybe (only in case of an error) we could point to a dedicated troubleshooting page.
+1 

That sounds like a feasible user story for me!

Don't show links to docs in case to prevent all eventualities upfront, but show them when the user needs them. I will rephrase the issue. I like the troubleshooting page idea.

**Comment by nikku** [comment]
Only if we link it :).

**Comment by christian-konrad** [comment]
Thank you @nikku !

> Rename from Should point to to Cannot connect to. Let's assume that users, with their best intentions tried to enter valid values 

This is great reasoning. Thanks
