### ISSUE TITLE
Error using template

### ISSUE THREAD

**Issue by Arcun91** [camunda/camunda-modeler#3616]
### Describe the bug

On modeler 5.11.0 i've a problem when using a SequenceFlow template. Importing the template cause an "Ooops, this should not have happened" error.

[C:\Users\bob\Desktop\test8.bpmn] Cannot read properties of undefined (reading 'toLowerCase')
    at toLowerCase (webpack://camunda-modeler-client/src/app/tabs/panel/tabs/LintingTab.js:110:12)
    at file:///C:/Users/bob/camunda-modeler-5.11.0/resources/app.asar/public/647.js:1:9839
    at Array.sort (<anonymous>)
    at file:///C:/Users/bob/camunda-modeler-5.11.0/resources/app.asar/public/647.js:1:9799
    at reports (webpack://camunda-modeler-client/src/app/tabs/panel/tabs/LintingTab.js:54:18)
    at c (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:150:95)
    at hg (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:166:272)
    at file:///C:/Users/bob/camunda-modeler-5.11.0/resources/app.asar/public/bundle.js:2:1099420
    at a (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:232:24)
    at bi (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:233:283) [ error ]

### Steps to reproduce

1. create the template 
{
        "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
        "name": "StepBack",
        "id": "com.bob.sequenceFlow.stepBackNoListner",
        "appliesTo": [
          "bpmn:SequenceFlow"
        ],
        "properties": [
          {
            "label": "StepBack",
            "type": "String",
            "editable": false,
            "value": "= __STEPBACK__",
            "binding": {
              "type": "property",
              "name": "conditionExpression"
            }
          }
        ]
      }
2. create a new bpmn and connect two service task with this edge
3. when using the template modeler show the error

Am I doing something wrong?

### Expected behavior

I expect to use the template without error

### Environment

- OS: [Windows 10 Pro]
- Camunda Modeler Version: [5.11.0]

**Comment by barmac** [comment]
Thanks for reporting! I can reproduce the issue.

**Comment by philippfromme** [comment]
Probably related to https://github.com/camunda/camunda-modeler/issues/3637.

**Comment by philippfromme** [comment]
So after handling rule errors we can see that every single rule throws an error. Not good. Will look into that.

![image](https://github.com/camunda/camunda-modeler/assets/7633572/90db30c6-9ca9-4ca4-8677-7302011107d7)

**Comment by philippfromme** [comment]
The issue is that the property `conditionExpression` is not a simple string property but a model element of the type `Expression` (cf. https://github.com/bpmn-io/bpmn-moddle/blob/master/resources/bpmn/json/bpmn.json#L1642). The element template is broken. We don't catch this during validation because we don't check against the [meta model](https://github.com/bpmn-io/bpmn-moddle/blob/master/resources/bpmn/json/bpmn.json). We also cannot handle expressions at the moment since we don't have a specialized handler for these as we do for other complex properties like inputs and outputs (cf. https://github.com/bpmn-io/bpmn-js-element-templates/tree/main/src/cloud-element-templates/create).
