### ISSUE TITLE
Documentation field Roadmap?

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-modeler#366]
is there any roadmap for the documentation field?

Thinking: support of Markdown, multi-line/CDATA?

Is there any preference to storing Documentation directly in the BPMN file or storing in external files and have a link inside of the BPMN?

Thanks

**Comment by nikku** [comment]
State of the union: The documentation field is accessible / editable for all BPMN elements.

We do not have any any Roadmap evolving the documentation beyond that point. Depending on your use case it might make more sense to store the documentation in an external place and simply link it from the documentation field. 

Markdown support for documentation sounds like an interesting feature because it solves simple layouting / external links nicely.

A few issues I can think of here:

* users should be able to use markdown on an opt-in basis (default should remain plain text)
* users should be able to switch between view / edit mode
* footprint should remain small

We appreciate a PR on this.

Closing this ticket for now, as we do not plan to do anything here in the near future.
