### ISSUE TITLE
Feel expression from output data doesn't work on Message Correlation key

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-modeler#3728]
### Describe the bug

When I enter a message correlation key, it doesn't propose the output value from my start event.

### Steps to reproduce

1. enter Example output on the start event like `{"businessKey":1}`.
2. add a task to the model
3. model an attached message boundary event.
4. create a new message with some name
5. enter `bu` as the correlation key.

### Expected behavior

The FEEL expression support suggests `businessKey`.

### Environment

Camunda Modeler system information
 * Version: 5.13.0
 * Operating System: Windows 10 amd64
 * Plugins: Cloud Connect, bpmn-js Token Simulation, Migration, Transaction Boundaries, Camunda Property Infos, Tooltip Plugin
 * Execution Platform: BPMN - Camunda Platform 8

### Additional context

It doesn't work for an output mapping either.

**Comment by philippfromme** [comment]
I can reproduce the behavior. @marstamm is this expected behavior or a bug? I'm not sure.

**Comment by marstamm** [comment]
This is expected behavior as we scope the example data to the element. To make the `businessKey` availabe to the process, add an output mapping with the same name to the Start event:
![image](https://github.com/camunda/camunda-modeler/assets/21984219/d56d9a4e-bbcb-43cb-8cab-7b945f2c9778)

Then the variable can be used in Messages 
![image](https://github.com/camunda/camunda-modeler/assets/21984219/30bd1988-e7d5-4485-999d-6c7543f6c89a)

cf. https://docs.camunda.io/docs/components/modeler/data-handling/

Related to https://github.com/camunda/camunda-modeler/issues/3524 , https://github.com/camunda/camunda-modeler/issues/3525

**Comment by marstamm** [comment]
This is mostly a technical limitation imposed by connectors, as they have non-standard variable scope and mapping behavior which is hidden in the connector runtime. Basically, connector mappings are not clearly defined and example data could wrongly leak into suggestions for further elements.

So, to prevent wrong suggestions, we used the "rather save than sorry" approach and only suggest variables which we are sure are present. This requires explicit variable mappings on all elements.

I understand that this is not ideal UX. The Connectors team is aware of the issue, I am not sure of the current state or priority. Thank you for the feedback, we can reconsider the approach once Connectors has clearly defined mapping/scope behavior. I'll keep this ticket open to revisit then. The whole discussion/backgronund can be found in https://github.com/camunda/camunda-modeler/issues/3524

**Comment by nikku** [comment]
> In my example: When the businessKey arrives as the payload of an intermediate message event in the second half of the process in my process instance, it is counterintuitive to add it on the process level in the start event.

I think this is important, UX wise and also where we want to go in the future. As of today output mappings are performed internally by connectors, and we cannot reliably interpret them.
