### ISSUE TITLE
Problem wrongly reported with missing time to live

### ISSUE THREAD

**Issue by cybermotier** [camunda/camunda-modeler#3853]
### Describe the bug

Editing a BPMN, a problem is reported for the BPMN with the Time to live field marked as invalid. The displayed message is: Time to live must be defined.
But a value (14) was set.

### Steps to reproduce

1. Open a BPMN
2. Invoke Save
3. Time to live field displayed as missing when a value is provided

### Expected behavior

No problem report

## Camunda Modeler system information
 * Version: 5.15.0
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Platform 7

**Comment by smbea** [comment]
Thanks for reporting, I can reproduce the issue. We'll look into it.

**Comment by marstamm** [comment]
[Root Cause]

Soooo, usually we reuse the parsed moddle when we do the linting, [but on save we only pass the XML](https://github.com/camunda/camunda-modeler/blob/4b2291a0bf6e015b2f1b5a8947660baa7b2eb03b/client/src/app/App.js#L994). That means that we need to parse it in linting. For some reason, [we do not have the camunda moddle extension in `@camunda/linting`](https://github.com/camunda/linting/blob/648fc45b9921c65ff83f984d23f5a68c20f339f0/lib/Linter.js#L22-L25), so all `camunda:` properties are ignored. So this should be as simple as adding a moddle extenstion to `@camunda/linting`

**Comment by philippfromme** [comment]
> For some reason, [we do not have the camunda moddle extension in `@camunda/linting`](https://github.com/camunda/linting/blob/648fc45b9921c65ff83f984d23f5a68c20f339f0/lib/Linter.js#L22-L25), so all `camunda:` properties are ignored. The fix should be as simple as adding a moddle extenstion to `@camunda/linting`

Ooopsie!

**Comment by marstamm** [comment]
As it turns out, it is not as simple as adding another extension. As described in https://github.com/bpmn-io/moddle/pull/45, moddle does not allow you to have attributes with the same name, even in different namespaces. Unfortunately, we do have overlaps for `modelerTemplate` attributes.

As a workaround, we can provide the diagram type (C7/C8) in the tab Config and select the needed moddle extension: https://github.com/camunda/camunda-modeler/blob/3356ba88337901cee8296751f3e243d6390d2b37/client/src/app/TabsProvider.js#L248-L251
