### ISSUE TITLE
Transform Connector to Service Task

### ISSUE THREAD

**Issue by astrothmann** [camunda/camunda-modeler#4070]
### Describe the bug

A connector task within your bpmn model is not able to be transformed to a plain service task.

![grafik](https://github.com/camunda/camunda-modeler/assets/65155273/b232d5bc-411e-40f1-8df8-54e1cd2f493e)

### Steps to reproduce

1. Inject element template of the [Whatsapp-Connector](https://github.com/camunda/connectors/blob/main/connectors/whatsapp/element-templates/whatsapp-connector.json)
2. create a bpmn model
3. include a connector as part of your model
4. change the type of that connector to be a service task
5. observe this transformation to be not happening

### Expected behavior

I'd expect the connector to be transformed into a service task without any errors occuring.

### Environment

- OS: MAC OS
- Camunda Modeler Version: 5.19.0
- Execution Platform: Camunda 8

**Comment by nikku** [comment]
@astrothmann This is likely a regression introduced with `v5.19.0`, to be fixed with `v5.20.0`, cf. [upstream bug report](https://github.com/bpmn-io/bpmn-js/issues/2073).

Could you verify this works fine in v5.18.0? We'll also ensure that we update the nightly with the latest versions so you could double check there.
