### ISSUE TITLE
Export diagram as WORD and PDF

### ISSUE THREAD

**Issue by kbhogadi** [camunda/camunda-modeler#4107]
### Problem you would like to solve

Please extend the capability to export process modals in different useful formats like WORD & PDF. 

### Proposed solution

This feature would be very useful for business users if Camunda Modeler has this important capability to export BPMN modal diagram along with it's text documentation in Word or PDF format. This feature available in IBM Blue Works Live and users use this feature to export and convert their process flows into requirements document.

### Alternatives considered

It's useful to have Word and PDF options in Camunda Modeler Opensource export functionality.

### Additional context

Hope this feature will be implemented and available in the later camund modeler versions.Thank You !

**Comment by barmac** [comment]
What should such a documentation document include? What problem does it solve?

**Comment by nikku** [comment]
I believe there is tools on the market that allow wrapping an image (or SVG) in a PDF automatically. We'll not offer this functionality without clear understanding of the value it offers (over simply embedding the actual diagram using [`bpmn-js`](https://github.com/bpmn-io/bpmn-js)). Closing this issue as `won't fix`.

**Comment by ferstring73** [comment]
I will talk as a Process Analyst. When we are modeling a process, we are also documenting it to explain details about how each task must be executed, who is responsible for it and its inputs and outputs. 
Next the process must be validated by all participants that must read and give their opinion about it. Usually the participants are not process analysts and most of them will not open a modeler or navigate in a web portal with several clicks at this moment. Mainly the managers, the boss that need to read and approve many processes. 
The most of the people wants to open a PDF and quickly scroll and read the details of each task, mainly that tasks that he is the participant responsible, in the moment of validation, or in the moment they want to have a complete view of the process. Additionally many processes are design to attend compliances, or to be used as requirements specification, and formal documentation are required to be signed by managers and/or customers.  
In another phase, when the process are being executed and monitored, then a web view in which the user can click in the tasks is more pratical. 
It is important that the modeler have a funcionality in which the 'element documentation' can also printed together with the model, when desired.
I am a new user of Camunda, but one of the first things I was looking for is how the Camunda exports the processes documentation because this is a functionality that saves a lot of time and redundant work. If we don't have someting like this, we need to maintain in paralell the ellaboration of the documentation of each process - what open space for synchronization/version issues. We can make the most of the process versioning of Camunda if we can export the model with the documentation.
Bizagi Modeler is an example of tool that provides exportation in several formats: "static format" Word or PDF and "web interative format" in HTML.

**Comment by barmac** [comment]
Thanks for the explanation. I think this is a good idea for a community extension. Not sure whether we'd like to have that in the core, but I'll CC @crobbins215 to evaluate.

**Comment by danielcolm** [comment]
Adding to what @ferstring73 proposed (which I 100% support as a business consultant), a step up compared to Bizagi (which I'm currently using) and the current proposal would be to allow for exports to a web text management system. With Word I would share the export with the client, collect feedback via In-Word-Comments (best case scenario) and than manually adjust the source documentation in the BPMN editor. 

Wouldn't it be possible to show the documentation creating a view, accessible via browser? As an editor I would choose which fields to show (e.g. Titles and Descriptions). The viewers would find a sequence of task titles and descriptions and have the possibility to comment or suggest edits. This should flow back to me on the model, allowing for faster edits that are then reflected in real time on the readers view.

Versioning each item, you would allow for much simpler handling of document approval processes.
