### ISSUE TITLE
importXML invoked from plugin updating diagram but not XML representation

### ISSUE THREAD

**Issue by daraghhiggins12** [camunda/camunda-modeler#4130]
I have built a camunda plugin and gained access to the modeler instance using the 'bpmn.modeler.created' event.

When invoking importXML on the instance the diagram is updated with the model representation of the XML however when switching to the XML visualisation the XML equivalent is not updated.

### Steps to reproduce

1. Access modeler from plugin using 'bpmn.modeler.created' event
2. invoke importXML with some XML
3. Notice the diagram updating in the modeler but the XML representation not being updated

### Expected behavior

I expect that when importing a model to the canvas successfully that the XML visualisation represents the model

### Environment

- OS: MacOS
- Camunda Modeler Version: 5.14.0
- Execution Platform: Camunda 7

**Comment by nikku** [comment]
@daraghhiggins12 What you're doing is not a recommended usage of our plug-in system. If you want to update the contents of a file that the editor _sees_ then you won't update the diagram contents, but the file contents. 

Let's also discuss what you want to accomplish (and why). What do you want to accomplish? We're happy to support you.

**Comment by daraghhiggins12** [comment]
I want to develop a plugin that is capable of loading models from an external source and when I select a model I can see it on the canvas

**Comment by nikku** [comment]
What is your approach? Is there an example you can share? The editor interacts with _files_ and you would need to play nicely with that abstraction in order to get things updated properly. I'd recommend you to look into [`MultiSheetTab`](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/MultiSheetTab.js#L85) to see how updating of different tabs works (the BPMN editor notifies the app when it changed, and the XML can update accordingly).
