### ISSUE TITLE
Add DMN row editor to show/edit row id

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda-modeler#4197]
### Problem you would like to solve

When writing unit tests for DMN, I would like to assert that a specific rule (identified by its id) is hit.
This id should be visible in the editor, not only in the xml structure.

### Proposed solution

Introduce a row editor (like the one for a column), that allows for inspecting / editing the row id

### Alternatives considered

no

### Additional context

https://camunda.slack.com/archives/C0693F1NFK5/p1710753897911279

**Comment by nikku** [comment]
Thanks for opening this issue. What specific test framework do you use? I believe we want to consider this end-to-end:

* Either this is a none feature, because we test "integration style" using combinations of `[inputs, expectedOutputs]` 
* Or this is actually a feature ("unit test style"), asserting the nitty gritty

I'd personally tend to call this a "bad testing practice" when the alternative is to use test data from a larger test bed, i.e. a CSV, and check that `IN > OUT` assertions are matched.

**Comment by nikku** [comment]
I gave this another thought and will close this as _not planned_.

We already know that integration tests beat unit test in terms of robustness, so we'll not encourage any kind of fragile testing practice.

The core editor (dmn-js) is extensible, so if for whatever reason you consider this style of testing mandatory, then you can extend it to expose these implementation details to your users.

Keep in mind that IDs are optional for rows, so you may be lucky and have the rows annotated.
