### ISSUE TITLE
Exporting to PNG/JPG does not work

### ISSUE THREAD

**Issue by kriskot** [camunda/camunda-modeler#420]
Hi,

when I export BMPN model to image, the program creates always 300x150 blank (white) img, no matter how big was the model.
- CamudaModeler v.1.3
- Windows 7

I downloaded .exe file, didn't build it by myself.

---

See also [SUPPORT-2751](https://app.camunda.com/jira/browse/SUPPORT-2751), [SUPPORT-2789](https://app.camunda.com/jira/browse/SUPPORT-2789).

**Comment by ricardomatias** [comment]
It works for me in Linux. Please try downloading [this](http://demo.bpmn.io/s/pizza-collaboration) diagram and export it as an image.

**Comment by kriskot** [comment]
Yep, your example works fine but when you edit both your and my files you can see the namespaces are different.

Pls have a look at this example produced on my machine:
[MFA2.bpmn.txt](https://github.com/camunda/camunda-modeler/files/502315/MFA2.bpmn.txt)

**Comment by mcirikovic** [comment]
Hi,

i have the same problem. It works for some models, but others (all created within the last 3 month) produce a white empty image. SVG works.

On multiple PCs, also downloaded:
1) Windows 10, Modeler v1.3 
2) Windows 10, Modeler v1.3.2.

**Comment by kriskot** [comment]
For me SVG generates file with content but it looks like not a proper .svg format, at least for IE and VSCode...

**Comment by ricardomatias** [comment]
@kriskot I've tried with your file and indeed it doesn't work. Therefore I've added a "Bug" label, we'll take a look into it.

**Comment by 341bms** [comment]
Same problem here on Win/Mac with models created/saved with CamudaModeler >= v.1.3. Exports only blank images.

**Comment by nikku** [comment]
@341bms If possible, please share the diagram that yields this behavior.

**Comment by 341bms** [comment]
Able to reproduce the problem. Attached are to models. "diagram_non_exportable.bpmn" exports a blank image. In "diagram_exportable.bpmn" the gateway name is changed an now the image export works. Something regarding special chars or char encoding?

[Archiv.zip](https://github.com/camunda/camunda-modeler/files/508089/Archiv.zip)

**Comment by seanblumenfeld** [comment]
Hi,

I am seeing the same problem on an Ubuntu 14.04 machine.  I presume this is not just specific to windows machines.

**Comment by samizzle** [comment]
Same issue on v1.3.2 for Mac OS Sierra. It did work to begin with a few times for PNG at least. At some point along the way it stopped working.

I have tried the following:
1. Upgrading to v1.4
2. Copying the BPMN diagram to a fresh diagram canvas, saving and then retrying the export.
3. Saving the diagram as a new name and then retrying the export.

None of these troubleshooting steps generate a PNG or jpg.

Workaround I am using at the moment is screenshot.

**Comment by mschulte** [comment]
Hey together,

i ran into this lately in a customer project. I tried to build a minimum reproducable example. 
First i thought the issue may be related to using a german "umlaut" in process element names. 
However i think it is caused by trailing whitespaces.

See my files for reference:
I got the following sample process diagram:
![running version](https://cloud.githubusercontent.com/assets/843635/19769648/8d76bbb4-9c5c-11e6-830d-0fca5405cc57.png)

Minimum reproducable example files:

- works:
 [running version.bpmn.txt](https://github.com/camunda/camunda-modeler/files/556011/running.version.bpmn.txt)

- doesn't work: 
[corrupted version.bpmn.txt](https://github.com/camunda/camunda-modeler/files/556010/corrupted.version.bpmn.txt)

Looking at the difference between those two files i found out that the CallActivity in the corrupted file looks like `<bpmn:callActivity id="ServiceTask_0qcbs4y" name="Bonitätsprüfung ">`, removing the trailing whitespace (`<bpmn:callActivity id="ServiceTask_0qcbs4y" name="Bonitätsprüfung">` ) leads to the running version that will export my process model to PNG.

This is reproducable with every bpmn-element (events, activities, sequence Flows) i tried. 
A trailing whitespace always leads to a situation where the export is not possible at all.

Any chance to dive into this? Maybe "trim" whitespaces before exporting as a workaround?

Kind regards,
Matthias

**Comment by mcirikovic** [comment]
The space at the end was a good hint, but did not fix all of my models. I then digged deeper and found the reason why it wasn't working for me:

A normal space is **0x20** in HEX, but if the name contains an non-breaking space (**0xC2 0xA0**), the model breaks.
![special whitespaces](https://cloud.githubusercontent.com/assets/17272023/19814783/154241b0-9d40-11e6-8da8-6f8faff00642.PNG)

**Comment by walter2** [comment]
I experienced the same problem with blank .png/.jpeg exports.
On Ubuntu 16 a workaround is to export an .svg first and then to convert it with `convert NAME.svg NAME.png` to pgn.

**Comment by StephenOTT** [comment]
experiencing on Mac

**Comment by StephenOTT** [comment]
I was able to resolve the issue while inspecting with Firefox the SVG.  

I have a annotation with the following text:
```
Reviews Request.  Reviews avalibility and purpose.  If approved, selects time slot and provides comments/text.  If denied, provides reasons for denial.  Can offer another time slot.
```

Was getting an error when rendering the SVG in the Browser:

```
This page contains the following errors:

error on line 4 at column 41910: Entity 'nbsp' not defined

```

Firefox identifies the location:

```
</tspan><tspan x="5" y="93">denial. &nbsp;Can offer another time slot. </tspan></text></g>
```

CMD+C the annotation text, and then deleted the annotation.  Then readied the annotation and pasted the exact text back in.  And the problem was resolved.  I made zero edits the formatting or text content.

**Comment by ricardomatias** [comment]
I can no longer reproduce this bug with the provided diagrams in Linux or macOS. I used the upcoming version 1.5 to test.

**Comment by walter2** [comment]
@ricardomatias 
Many thanks. When will that version be fully released?

**Comment by ricardomatias** [comment]
You can download it from [here](https://camunda.org/release/camunda-modeler/1.5.0/).

**Comment by walter2** [comment]
Many thanks @ricardomatias. 
The export works fine again.
