### ISSUE TITLE
Change in Multi-Instance marker should retrain Property Data

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler#4310]
### Problem you would like to solve

When creating a multi-instance activity selecting the mulit-instance parallel marker (for example) then displays the properties required for execution of that symbol. When you change the symbol to multi-instnace sequential marker all data entered in those properties are removed even though both markers require the same properties. 
![image](https://github.com/camunda/camunda-modeler/assets/10612634/a0a6192b-0078-472b-baa9-34e0e42d644e)

### Proposed solution

Retrain properties when switching between multi-instance markers

### Alternatives considered

Only copying all the data manually before switching over. Or copying the element itself to retain the information

**Comment by nikku** [comment]
Thanks for opening this bug. I agree that all properties that are applicable in both scenarios shall be retained (cf. [design principles](https://github.com/bpmn-io/design-principles?tab=readme-ov-file#do-the-hard-work-to-make-it-simple)).

We'd want to fix this in a dedicated replace behavior in either [bpmn-js](https://github.com/bpmn-io/bpmn-js) or [camunda-bpmn-js-behaviors](https://github.com/camunda/camunda-bpmn-js-behaviors).

**Comment by philippfromme** [comment]
### Root cause analysis

Properties like _Input collection_ are part of a `zeebe:LoopCharacteristics` extension element. Our [behaviors](https://github.com/camunda/camunda-bpmn-js-behaviors/blob/main/lib/camunda-cloud/CopyPasteBehavior.js#L112) look into the `allowedIn` property ([defined in `zeebe-bpmn-moddle`](https://github.com/camunda/zeebe-bpmn-moddle/blob/main/resources/zeebe.json#L189)) to figure out whether a property can be copied to a new target. Our convention is that the types in `allowedIn` refer to flow elements (e.g. `bpmn:ServiceTask`). The behaviors then check whether the parent flow element of the new element the property is to be copied to is one of these flow elements. When using the replace feature this is fine because the parent exists. However, [when changing the loop characteristics without replacing the flow element the new element doesn't have a parent at the time of the check](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/popup-menu/ReplaceMenuProvider.js#L488). The behaviors therefore don't allow copying the `zeebe:LoopCharacteristics` extension element.

### To do

* do not create a new `zeebe:LoopCharacteristics` element when changing between non-sequential and sequential (will fix the issue without addressing the root cause)
* consider changing the `allowedIn` property of `zeebe:LoopCharacteristics` to refer to the `bpmn:MultiInstanceLoopCharacteristics` element instead of the flow element (assumes that `zeebe:LoopCharacteristics` is always allowed if `bpmn:MultiInstanceLoopCharacteristics` is allowed)
