### ISSUE TITLE
Diagram fails to open in application (breaks it)

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#4473]
### Describe the bug

I try to open the [following BPMN diagram](https://github.com/user-attachments/files/16690372/linting-no-id-name.bpmn.txt) and it breaks the application. 

I only see a blank screen, and cannot to use the app. Due to the fact that "last opened diagrams" is remembered, I cannot easily recover from this, too.

### Steps to reproduce

1. open [test diagram](https://github.com/user-attachments/files/16690372/linting-no-id-name.bpmn.txt)
3. observe crash (blank screen)

### Expected behavior

* [ ] Diagram opens, validation errors (if any) show.

### Environment

- OS: Linux, Ubuntu 22
- Camunda Modeler Version: v5.25.0
- Execution Platform: any
- Installed plug-ins: none

### Additional context

Questions:

* Why do our existing error boundaries not work, is there something we can improve to prevent such crash?

**Comment by nikku** [comment]
Root cause:

* When sorting lint errors we assume that either `id` or `name` is present on reports, which is not the case if `no-bpmn-di` reports "missing DI"
* This crashes during sorting

**Comment by nikku** [comment]
Moving to `ready` due to impact.

**Comment by jarekdanielak** [comment]
The root cause is fixed in https://github.com/camunda/camunda-modeler/pull/4518

The error is actually caught in `componentDidCatch` of App component, but it goes into an infinite loop. My idea would be to have the bottom panel container closed in its own error boundary so that if it crashes, it doesn't take the whole app with it. Not sure if we want to investigate it now tough.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/4518
