### ISSUE TITLE
unsaved changes mode toggled although nothing has changed

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#543]
Reproduce:
Fails randomly. Possible steps to reproduce:
- Create new DRD
- Change decision table name
- Save file
- Open decision table
- Click 'Show DRD' in a decision table that has no unsaved changes
or
- Create new DRD
- Change the ID
- Save file
- Open XML view

Problem:
unsaved mode toggled although nothing has changed

**Comment by philippfromme** [comment]
Can not reproduce using Camunda Modeler 1.9.0 and Windows 10. @pedesen, please check if you can reproduce.

This might have been already fixed by https://github.com/camunda/camunda-modeler/commit/f874f51d7202e0459ddd33b10a5a87cdde22e7df which fixed a similar [issue](https://github.com/camunda/camunda-modeler/issues/563). Especially the fact that this occurs randomly is a strong indicator that it happens for the same reason as https://github.com/camunda/camunda-modeler/issues/563 did.
