### ISSUE TITLE
unsaved changes mode not toggled although file has changed

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-modeler#545]
Reproduce
- create new DRD file
- save the file
- open decision table and enter name
- save the file
- rename id
- click show drd

Problem:
- unsaved changes mode is not toggled

**Comment by philippfromme** [comment]
Can not reproduce using Camunda Modeler 1.9.0 and Windows 10. @pedesen, please check if you can reproduce.

This might have been already fixed by https://github.com/camunda/camunda-modeler/commit/f874f51d7202e0459ddd33b10a5a87cdde22e7df which fixed a similar [issue](https://github.com/camunda/camunda-modeler/issues/563).
