### ISSUE TITLE
Enable converting/importing bpmn-files which contain activities with a prefix

### ISSUE THREAD

**Issue by elgubenis** [camunda/camunda-modeler#606]
Issue: https://app.camunda.com/jira/browse/SUPPORT-3408

Currently when importing a bpmn-file which contains a prefix inside the activity an error is thrown,
a temporary workaround is to remove all prefixes before importing.

We should discuss:
1. removing those prefixes automatically for the user
2. or to have a prompt asking the user if he wants the modeler to remove those before importing.

I also do not know if for some reason the user would actually like to keep reference to that namespace and though should not be removed but suggest the user itself to prepare the bpmn-file accordingly (Please remove all prefixex,... kind a thing)

example task code which makes the import fail:
```
<bpmn2:userTask id="Contract" activiti:assignee="lrzwxyz" name="Contract">
    <bpmn2:incoming>SequenceFlow_1</bpmn2:incoming>
    <bpmn2:outgoing>SequenceFlow_2</bpmn2:outgoing>
</bpmn2:userTask>
```
In this case the ```activiti:```-namespace is throwing the error, if it's removed the import succeeds.

**Comment by pedesen** [comment]
There is already a dialog showing up, if the diagram contains an activiti namespace. If you confirm, the definition `xmlns:activiti` is converted to `xmlns:camunda` in the root `bpmn:definitions` tag, but the properties prefixes are not converted, which causes the import error.

We could convert all `activiti` prefixes along with the namespace to `camunda` (`activiti:assignee` would become `camunda:assignee` and so on).

This conversion would fit the customer's requirements most, because
* he has the choice whether he wants to convert the activiti namespace and prefixes, or keep it
* all properties from the old diagram are retained
* no need to manually replace stuff in the xml

But I'm not sure, if all possible activiti properties are supported with a camunda prefix as well.

**Comment by pedesen** [comment]
We already have all this implemented, it was just a bug, where the prefix `activiti` was not correctly grabbed from this definition: `xmlns:activiti="http://camunda.org/schema/1.0/bpmn"`. This now imports without error and converts to `xmlns:camunda="http://camunda.org/schema/1.0/bpmn"`.

**Comment by elgubenis** [comment]
Reviewed, lgtm.
