### ISSUE TITLE
Opening file does not show Camunda Modeler application on Mac

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#632]

**Comment by tasso94** [comment]
If a file is opened via Finder...

# Expected behavior
...the window with the respective file comes to the foreground.

# Observed bahavior
...the file is opened in camunda modeler but the window stays in the background. The user is not notified that the action he performed actually took place.

![ezgif-4-d80a6c3f0c](https://user-images.githubusercontent.com/3015690/28865964-d5f3302a-7771-11e7-95aa-1267664b8573.gif)

**Comment by nikku** [comment]
Is this still an issue?

**Comment by tasso94** [comment]
Hey Nikku,

I just tested it with 1.16.2 and it is still an issue.

Cheers
Tassilo

**Comment by nikku** [comment]
@pinussilvestrus Is this still an issue in `v3.x.x`. I remember we did some improvements in that area.

**Comment by pinussilvestrus** [comment]
Yes, it is fixed. I remember @barmac and I solved it  in a reviewing session (cf. eff83531b0d5a7d2735f3f4987048d47743e1f9d)

Therefore closed via eff83531b0d5a7d2735f3f4987048d47743e1f9d

**Comment by nikku** [comment]
Thanks! 

:cake:
