### ISSUE TITLE
Several DMN TCK models are not detected as DMN

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler#761]
https://github.com/dmn-tck/tck/blob/master/TestCases/compliance-level-3/0014-loan-comparison/0014-loan-comparison.dmn
https://github.com/dmn-tck/tck/blob/master/TestCases/compliance-level-3/0030-user-defined-functions/0030-user-defined-functions.dmn
https://github.com/dmn-tck/tck/blob/master/TestCases/compliance-level-3/0031-user-defined-functions/0031-user-defined-functions.dmn

![2018-03-23 - seleccion 004](https://user-images.githubusercontent.com/40038/37843372-fd7108f6-2ec4-11e8-83b9-f351a2afeb6a.png)

**Comment by nikku** [comment]
These diagrams are detected as DMN, as indicated by the error message `no view to display` we simply don't find anything to display in these diagrams:

* no decision backed by decision table or literal expression 
* no DRD with DI attached

What is the expected behavior when faced with these kinds of diagrams? Open the DRD with an empty canvas?

**Comment by nikku** [comment]
Changed the default open behavior via https://github.com/bpmn-io/dmn-js/commit/fea3f5aa43024a7c42cacb6d567401d4d64b1f81. 

The relevant diagrams will be opened now with numerous warnings though. This is due to the fact that our DMN model does not seem to be complete (different issue).

**Comment by falko** [comment]
Thx!
