### ISSUE TITLE
A logging system for plugins ?

### ISSUE THREAD

**Issue by itisntalex** [camunda/camunda-modeler#767]
**Context**

I'm currently working on a camunda-modeler plugin as part of my university research project and I faced some issues while debugging my simple plugin - It was in fact a simple plugin that adds menus. It turns out, the problem I faced while debugging my plugin was the lack of information on why it didn't work. Did I mess up code ? Did I installed the appropriate packages ? And so on...

**Proposition**

To solve this issue and ease the development process of new plugin I'm proposing a simple concept. A logging system. With a logging system, it could be possible to have an output on what went wrong in your plugin and then fix it. However, there is a question that needs to be addressed. Which component is responsible of the logging stuff:
* Is it the modeler
* Or is it the plugin
* Or may be both of them ...?

**Comment by philippfromme** [comment]
We actually have a logging system in the Camunda Modeler. You can see it in action when your opening the developer tools using F12. As for logging in your plugin I guess you have to take of that yourself since we can't make any assumptions about what you're doing with your plugin. Notice that you can always use the developer tools to debug and see what is going on.
