### ISSUE TITLE
Colapse pool and expanded pool does not visualise the Bp in the colapsed/expanded pool

### ISSUE THREAD

**Issue by mabayona** [camunda/camunda-modeler#771]
It happened in previous camunda-modeler version and it still happens in the new 1.12.0:

if a pool containing a BP is collapsed and then expanded, the expanded pool does not show the BP. It just shows an empty pool.

It happens in Ubuntu and in Windows.

**Comment by philippfromme** [comment]
What do you mean by `BP`. If you mean flow elements, the behavior you observed is correct. A collapsed pool doesn't contain any flow elements since it only represents a process we don't own so we don't know its inner workings.

There is no easy way to change this behavior.

We've already opened an [issue](https://github.com/bpmn-io/bpmn-js/issues/736) that addresses this.

I'm going to close this for now as has been addressed already.
