### ISSUE TITLE
Unsuccessful deployments show up as successful when deploying from modeler

### ISSUE THREAD

**Issue by benhoffmann** [camunda/camunda-modeler#838]
If I deploy a model directly from the modeler, it says "Deployment was done successfully" even if this was not the case. My engine complained with a BPMN parse error and did not deploy the diagram, but the modeler did not catch that problem.

v 1.16.0

**Comment by fractallian** [comment]
Would be extremely helpful to surface model parsing errors in the modeler. I see errors using the API but modeler just says deployment succeeds for the same file.

**Comment by Alexander-Kiselyov** [comment]
Perhaps, it happens because deployment endpoint responds with 2 HTTP statuses? E.g. this is what happens when I try to deploy a definition with a process-level Event Subprocess triggered by a Compensation Start Event (not supported [according to the doc](https://docs.camunda.org/manual/7.9/reference/bpmn20/events/cancel-and-compensation-events/)): first 100, and then 500 status is sent:
```
> POST /engine-rest/deployment/create HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Length: 12747
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------75a62bae9b8408af
>
< HTTP/1.1 100
< HTTP/1.1 500
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Sun, 23 Sep 2018 20:24:26 GMT
< Connection: close
<
{"type":"ProcessEngineException","message":"ENGINE-09005 Could not parse BPMN process. Errors: \n* event subprocess with compensation start event is only supported for embedded subprocess (since throwing compensation through a call activity-induced process hierarchy is not supported) | testprocess.bpmn | line 30 | column 48"}* Closing connection 0```

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1041.
