### ISSUE TITLE
Sequence flows to message events are not attached to center

### ISSUE THREAD

**Issue by stephanpelikan** [camunda/camunda-modeler#887]
If you use pools and visualize message flows by dragging dotting arrows to message events then those arrows are not attached to the center of that message event (see video: [Sequence flows to message events are not attached to center.zip](https://github.com/camunda/camunda-modeler/files/2309234/Sequence.flows.to.message.events.are.not.attached.to.center.zip)). You have to emend it manually. Sometimes it is only a little amount, so only orderly persons may see the effect, but sometimes it is easy to see for everyone. In some circumstances it is snapped exactly to the center but those situations are rare - generally it is not.

I use version 1.16.2

**Comment by nikku** [comment]
Thanks for reporting this issue.

The behavior itself is intentional, as users should be able to specify the exact docking position of the message flow on the target element. This is required for docking on tasks as seen in the screen cast below.

![foo](https://user-images.githubusercontent.com/58601/44454077-dd6b3d80-a5fa-11e8-9d65-84a20d269db2.gif)

One could argue that this "feature" makes no sense when connecting from / to events, as the resulting diagram is almost always ugly. I suppose consistent snapping to the elements center (c.f. snapping on sequence flow creation; second part of screen cast) would improve things?

**Comment by nikku** [comment]
Adding consistent snapping for message flows on creation is tracked via https://github.com/bpmn-io/bpmn-js/issues/850.
