### ISSUE TITLE
Element Templates in .camunda/element-templates directory does not work

### ISSUE THREAD

**Issue by pme123** [camunda/camunda-modeler#958]
__Describe the Bug__

According to the [documentation](https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates) this is possible:

> Alternatively, they can be stored in a .camunda/element-templates directory that resides, relative to the currently opened diagram, anywhere in the diagrams path hierachy.

This does not work.

__Steps to Reproduce__

1. add directory in the path where you have your diagrams:
![image](https://user-images.githubusercontent.com/3437927/47492421-41a1bc00-d84d-11e8-9e80-f2691bd2b8fa.png)

    I have diagrams in this folder as well in _features_. Both do not work.

2. Refresh the Modeler
3. Check if the Template Element is in the Dropdown

__Expected Behavior__

Templates in _.camunda/element-templates_ are available in the Modeler.

__Environment__
 - OS: Mac OS Moyave
 - Camunda Modeler Version: 1.15.1

**Comment by pme123** [comment]
also a problem with Camunda Modeler Version: 2.0.3

**Comment by nikku** [comment]
Did you store it in a library called `.camunda`? I don't see the dot in your project listing.

**Comment by pme123** [comment]
Ah - my fault - I interpreted that as ./camunda. 

It works now - but now the templates from the application (_camunda-modeler/resources/element-templates_) are not there anymore. Is this intended to have only one of these both possibilities.

**Comment by nikku** [comment]
It should search and collects templates from all path in the following order:

* userData
* app dir
* .camunda relative to diagram

Note that element templates are identified and overridden by ID.

**Comment by nedyalkonikolov** [comment]
There is a test for this feature (loading element templates from a directory relative to the diagram), but the test is using fake diagram object with a property "path"

https://github.com/camunda/camunda-modeler/blob/master/app/lib/client-config/__tests__/client-config-spec.js#L22-L25

therefore the code here:

https://github.com/camunda/camunda-modeler/blob/master/app/lib/client-config/providers/element-templates-provider.js#L40

passes the test.

Unfortunately the real object (diagram) does not have "path" property, but "file" object that have "path" property.

Code in element-templates-provider.js should 
be 
var localPaths = diagram && diagram.file ? parents(diagram.file.path) : [];

also test should be a little different ().

// given
var fakeDiagram = {
  file: {
    path: absPath('fixtures/project/bar.bpmn')
  }
};

P.S. I do not find a document how to contribute, therefore I'm writing in the issue instead of a pull request! I hope someone from the core team could make this little change.
